#!/usr/bin/env bash
# Verify the red-team enclave image: every tool present + runnable. Runs inside the
# image (network on here only so version checks that phone home don't hang; the
# ENCLAVE runtime runs it sealed via the broker). Usage: bash verify.sh
img="${1:-enclave-redteam:latest}"
echo "── verifying tools inside $img ──"
docker run --rm "$img" bash -lc '
  v(){ printf "  %-16s %s\n" "$1" "${2:-$(command -v "$1" >/dev/null && echo present || echo "── MISSING")}"; }
  echo "[recon]"
  v nmap "$(nmap --version 2>/dev/null | head -1)"
  v masscan "$(command -v masscan>/dev/null&&echo present||echo MISSING)"
  v subfinder "$(subfinder -version 2>&1 | grep -i current | head -1 || subfinder -version 2>&1 | head -1)"
  v httpx "$(httpx -version 2>&1 | head -1)"
  v naabu "$(naabu -version 2>&1 | head -1)"
  v nuclei "$(nuclei -version 2>&1 | grep -i current | head -1 || nuclei -version 2>&1 | head -1)"
  v katana "$(katana -version 2>&1 | head -1)"
  v dnsx "$(dnsx -version 2>&1 | head -1)"
  v amass "$(amass -version 2>&1 | head -1)"
  v gowitness "$(gowitness version 2>&1 | head -1)"
  echo "[web/fuzz]"
  v sqlmap "$(sqlmap --version 2>&1 | head -1)"
  v ffuf "$(ffuf -V 2>&1 | head -1)"
  v feroxbuster "$(feroxbuster --version 2>&1 | head -1)"
  v nikto "$(command -v nikto>/dev/null&&echo present||echo MISSING)"
  echo "[AD / cred]"
  v nxc "$(nxc --version 2>&1 | head -1)"
  v certipy "$(certipy --version 2>&1 | head -1 || command -v certipy)"
  v kerbrute "$(kerbrute version 2>&1 | grep -i version | head -1 || command -v kerbrute)"
  v secretsdump "$(command -v impacket-secretsdump secretsdump.py 2>/dev/null | head -1)"
  v bloodhound-ce-python "$(command -v bloodhound-ce-python bloodhound-ce 2>/dev/null | head -1)"
  v azurehound "$(azurehound --version 2>&1 | head -1 || command -v azurehound)"
  v ldapdomaindump "$(command -v ldapdomaindump)"
  v responder "$(command -v responder Responder.py /usr/share/responder/Responder.py 2>/dev/null | head -1)"
  echo "[exploit / C2]"
  v msfconsole "$(msfconsole --version 2>&1 | head -1)"
  v sliver-server "$(sliver-server version 2>&1 | grep -i -m1 version || command -v sliver-server)"
  v sliver-client "$(command -v sliver-client>/dev/null&&echo present||echo MISSING)"
  echo "[cracking]"
  v hashcat "$(hashcat --version 2>&1 | head -1)"
  v john "$(john 2>&1 | grep -i -m1 jumbo || echo present)"
  v hydra "$(hydra -h 2>&1 | grep -i -m1 hydra | head -1)"
  echo "[wordlists / collectors]"
  v seclists "$([ -d /usr/share/seclists ] && echo /usr/share/seclists || echo MISSING)"
  v rockyou "$(ls /usr/share/wordlists/rockyou* 2>/dev/null | head -1 || echo MISSING)"
  v SharpHound "$(ls /opt/collectors/SharpHound*.zip 2>/dev/null | head -1 || echo MISSING)"
'
