// VARVEL — novelcore: the pre-submission NOVELTY GATE core (pure — ZERO network, zero I/O).
// Born from the semrush duplicate (#2666357, 2026-08-31): we filed CORS origin-reflection +
// ACAO:credentials on admin.semrush.net — but the behavior was emitted by the Google IAP
// edge gate (x-goog-iap-generated-response: true) on UNAUTHENTICATED 302 responses, no
// authenticated data was ever read cross-origin, and the program already knew. This module
// is the machinery that refuses that class of wasted submission, as CODE:
//
//   1) EDGE-GENERATED-BEHAVIOR DETECTOR — when the tested response's headers show it was
//      generated by edge/gate infrastructure (x-goog-iap-*, x-cache/via from
//      cloudfront/akamai/fastly on the tested status, server: awselb, …) AND the tested
//      status is an unauthenticated challenge (302/401/403), the finding is auto-flagged:
//      edge-generated behavior on an unauth response — high duplicate/non-impact risk.
//      It passes ONLY with demonstrated cross-origin read of authenticated application
//      data (or the class-equivalent impact proof). No impact proof, no submission.
//   2) PER-CLASS IMPACT-EVIDENCE BAR (IMPACT_BAR) — CORS requires actual
//      authenticated-content read (header reflection is NOT impact); TLS/cert hygiene is
//      NEVER submittable; cookie-flags/clickjacking are ineligible on HackerOne by
//      default; SSRF requires an OOB callback proof (tools/oob.mjs exists for exactly
//      this); IDOR requires cross-account read/write of real victim data with garbage-ID
//      + unauth controls (the validator's v2 manhuaus doctrine, class-applied).
//   3) INTERNAL DEDUP — 64-bit SimHash over prior drafts/reports, so we never re-file our
//      own finding against a sibling host without noting it.
//   4) HACKTIVITY READER — parseHacktivitySearch() tolerantly reads H1's public GraphQL
//      hacktivity search shape (verified live 2026-08-31 through the ghost chain:
//      search(index: CompleteHacktivityReportIndex, query_string) → HacktivityDocument
//      nodes). Whatever it cannot parse lands EMPTY with a named gap — never invented.
//
// VERDICTS: CLEAR | REVIEW-NEEDED (candidate duplicates found — operator must resolve) |
// UNVERIFIABLE (the hacktivity search FAILED — stated loudly, never faked) | BLOCKED
// (hard bar failed: never-submittable class, platform-ineligible class, or missing
// class-required impact proof). BLOCKED outranks everything.
//
// HARD RULES:
//   1. PURE: no fetch, no http, no fs, no network of any kind in this file — the network
//      half lives in tools/novelgate.mjs. test/novelgate.test.mjs pins this with a static
//      scan. engine/bountyline.mjs imports this module and stays offline by doctrine.
//   2. HONESTY: a failed search is UNVERIFIABLE, a missing proof is MISSING, an
//      unparsable shape is a named gap. Nothing here ever upgrades a guess to a verdict.
//   3. Heuristics are DETERMINISTIC and pinned by tests: regex tables, not vibes.

import { createHash } from 'node:crypto';

// ---------------------------------------------------------------- verdicts + marker
export const VERDICTS = ['CLEAR', 'REVIEW-NEEDED', 'UNVERIFIABLE', 'BLOCKED'];
// Machine marker embedded in every rendered novelty section — queueProgram keys on it.
export const NOVELTY_MARKER = '<!-- novelgate:v1 -->';

// ---------------------------------------------------------- weakness classification
// Order matters: first match wins. tls before cookie so 'session cookie over TLS' noise
// doesn't misclassify; the bars are per-CLASS, not per-word.
export const WEAKNESS_CLASSES = [
  { klass: 'cors', re: /\bcors\b|cross[- ]origin|access[- ]control[- ]allow[- ]origin/i },
  { klass: 'ssrf', re: /\bssrf\b|server[- ]side request forgery/i },
  { klass: 'idor', re: /\bidor\b|insecure direct object|broken object[- ]level|\bbola\b/i },
  { klass: 'tls', re: /\b(tls|ssl)\b|certificate (?:transparency|mismatch|hygiene)|expired cert|\bhsts\b|weak cipher/i },
  { klass: 'cookie', re: /cookie (?:flags?|attributes?)|\bhttponly\b|\bsamesite\b|secure flag|missing (?:secure|httponly)/i },
  { klass: 'clickjacking', re: /clickjack|ui[- ]redress|x-frame-options|frame-ancestors/i },
];

// classifyWeakness(text) → 'cors' | 'ssrf' | 'idor' | 'tls' | 'cookie' | 'clickjacking' | 'other'
export function classifyWeakness(text) {
  const t = String(text || '');
  for (const c of WEAKNESS_CLASSES) if (c.re.test(t)) return c.klass;
  return 'other';
}

// ---------------------------------------------------------- per-class impact bar
// proofRes: ANY match = proof present. admissionRes: a draft's OWN admission that the
// proof does not exist — an admission VOIDS a coincidental regex hit (the semrush draft
// said "Not included: a post-authentication demonstration" — that honesty now hard-fails
// the bar instead of sailing through).
export const IMPACT_BAR = {
  cors: {
    required: 'authenticated-read',
    desc: 'demonstrated cross-origin READ of authenticated application data — reflected ACAO/ACAC headers on their own are configuration, not impact',
    proofRes: [
      /\bauthenticated\b[^\n]{0,120}\b(?:read|returned|captured|retrieved|exfiltrat\w+|observed|served)\b/i,
      /\b(?:read|returned|captured|retrieved|exfiltrat\w+|observed)\b[^\n]{0,120}\bauthenticated\b/i,
      /cross[- ]origin[^\n]{0,160}\b(?:response body|data theft|account data|pii)\b/i,
    ],
    admissionRes: [
      /\bnot included\b[:\s][^\n]{0,200}\bpost[- ]auth/i,
      /\bno (?:authenticated|post[- ]auth) (?:session|account|demonstration|proof)\b/i,
      /\bunauthenticated (?:responses?|position) only\b/i,
      /\bnever (?:read|retrieved)[^\n]{0,80}cross[- ]origin/i,
      /\bcan (?:confirm|verify) the post[- ]auth\b/i, // "your team can confirm post-auth" = WE did not
    ],
  },
  ssrf: {
    required: 'oob-callback',
    desc: 'a correlated out-of-band callback (tools/oob.mjs canary) — a blind payload with no callback is an unproven claim',
    proofRes: [
      /\b(?:oob|out[- ]of[- ]band)\b[^\n]{0,120}\b(?:callback|correlated|hit|received)\b/i,
      /\b(?:callback|canary)\b[^\n]{0,120}\b(?:correlated|received|recorded|hit)\b/i,
      /\binteractsh\b/i,
    ],
    admissionRes: [/\bno (?:callback|oob)\b/i, /\bblind\b[^\n]{0,80}\bunproven\b/i],
  },
  idor: {
    required: 'cross-account-with-controls',
    desc: 'cross-account read/write of REAL victim data, with garbage-ID and unauthenticated controls (the validator v2 paired-control doctrine applied to the class)',
    // ALL of these must match — an IDOR claim without its controls is hollow.
    allRes: [
      /cross[- ]account|other (?:user|account|tenant)|victim/i,
      /garbage[- ]?(?:id|control)|paired control|control (?:read|request)/i,
      /unauth(?:enticated)? control|sessionless control|logged[- ]out control/i,
    ],
    admissionRes: [/\bown (?:two )?accounts? only\b/i],
  },
  tls: {
    neverSubmittable: true,
    desc: 'TLS/certificate hygiene findings are never submittable — scanners emit them for free and every program has seen them all',
  },
  cookie: {
    platformIneligible: ['hackerone'],
    desc: 'cookie-flag findings are ineligible on HackerOne by default (platform standard) unless chained into demonstrated account impact',
  },
  clickjacking: {
    platformIneligible: ['hackerone'],
    desc: 'clickjacking is ineligible on HackerOne by default unless it demonstrates a concrete state-changing action on a sensitive page',
  },
};

// impactEvidence(klass, text, { platform }) → { ok, klass, required, matched, admitted, reason }
// 'other' carries NO bar (ok:true, required:null) — the validator gate already governs it.
export function impactEvidence(klass, text, { platform } = {}) {
  const bar = IMPACT_BAR[klass];
  if (!bar) return { ok: true, klass, required: null, matched: [], admitted: false, reason: 'no class-specific impact bar — the validator gate governs this class' };
  const base = { ok: false, klass, required: bar.required || null, matched: [], admitted: false, desc: bar.desc };
  if (bar.neverSubmittable) return { ...base, reason: `class '${klass}' is NEVER submittable — ${bar.desc}` };
  if (platform && (bar.platformIneligible || []).includes(platform)) {
    return { ...base, reason: `class '${klass}' is ineligible on ${platform} by default — ${bar.desc}` };
  }
  const t = String(text || '');
  const admitted = (bar.admissionRes || []).find((re) => re.test(t));
  if (admitted) {
    return { ...base, admitted: true, reason: `the draft itself admits the ${bar.required} proof does not exist (matched /${admitted.source}/) — an honest admission hard-fails the bar; obtain the proof or do not submit` };
  }
  if (bar.allRes) {
    const matched = bar.allRes.filter((re) => re.test(t)).map((re) => re.source);
    if (matched.length === bar.allRes.length) return { ...base, ok: true, matched, reason: `all ${bar.required} elements present` };
    return { ...base, matched, reason: `the ${bar.required} bar needs ALL of: cross-account victim data + garbage-ID control + unauth control — found ${matched.length}/${bar.allRes.length}` };
  }
  const matched = (bar.proofRes || []).filter((re) => re.test(t)).map((re) => re.source);
  if (matched.length) return { ...base, ok: true, matched, reason: `the ${bar.required} proof is present` };
  return { ...base, reason: `class '${klass}' requires ${bar.required}: ${bar.desc} — no matching proof found in the draft` };
}

// ---------------------------------------------------------- edge-generated behavior
// A response GENERATED BY edge/gate infrastructure is not the application speaking.
// Filing an edge gate's own challenge-page behavior as an application vulnerability is
// the exact duplicate class that burned the semrush submission.
export const UNAUTH_STATUSES = [302, 401, 403];
export const EDGE_SIGNATURES = [
  { id: 'google-iap-generated', header: 'x-goog-iap-generated-response', valueRe: /^true$/i, note: 'Google IAP GENERATED this response — the application never saw the request' },
  { id: 'google-iap', headerPrefix: 'x-goog-iap-', note: 'Google Identity-Aware Proxy header — the response is the IAP gate speaking, not the app' },
  { id: 'awselb', header: 'server', valueRe: /^awselb/i, note: 'AWS ELB generated the response (default error/challenge page)' },
  { id: 'cloudfront', header: 'x-cache', valueRe: /cloudfront/i, note: 'CloudFront edge cache/error response' },
  { id: 'cloudfront', header: 'via', valueRe: /cloudfront/i, note: 'CloudFront edge served this response' },
  { id: 'cloudfront-pop', header: 'x-amz-cf-pop', note: 'CloudFront PoP header — edge-served response' },
  { id: 'akamai', header: 'server', valueRe: /akamai/i, note: 'Akamai edge-generated response' },
  { id: 'fastly', header: 'x-served-by', valueRe: /cache-/i, note: 'Fastly edge cache response' },
  { id: 'cloudflare-challenge', header: 'cf-mitigated', valueRe: /^challenge$/i, note: 'Cloudflare issued a challenge instead of passing the request to the origin' },
  { id: 'incapsula', header: 'x-cdn', valueRe: /incapsula|imperva/i, note: 'Imperva/Incapsula edge response' },
];

// detectEdgeGenerated({ status, headers }) → { edge, unauthStatus, flagged, signals, reason }
// headers: a plain object (keys any case) OR a raw header block string. flagged = edge AND
// an unauthenticated challenge status — the semrush signature exactly.
export function detectEdgeGenerated({ status, headers } = {}) {
  const h = {};
  if (typeof headers === 'string') {
    for (const line of headers.split(/\r?\n/)) {
      const m = line.match(/^([A-Za-z0-9-]+)\s*:\s*(.*)$/);
      if (m) h[m[1].toLowerCase()] = m[2].trim();
    }
  } else if (headers && typeof headers === 'object') {
    for (const [k, v] of Object.entries(headers)) h[String(k).toLowerCase()] = Array.isArray(v) ? v.join(', ') : String(v);
  }
  const signals = [];
  const seenHeaders = new Set(); // one signal per header — an exact match and its prefix rule must not double-count
  for (const sig of EDGE_SIGNATURES) {
    if (sig.headerPrefix) {
      for (const [k, v] of Object.entries(h)) {
        if (k.startsWith(sig.headerPrefix) && !seenHeaders.has(k)) { signals.push({ id: sig.id, header: k, value: v.slice(0, 60), note: sig.note }); seenHeaders.add(k); break; }
      }
      continue;
    }
    if (!(sig.header in h) || seenHeaders.has(sig.header)) continue;
    if (sig.valueRe && !sig.valueRe.test(h[sig.header])) continue;
    signals.push({ id: sig.id, header: sig.header, value: h[sig.header].slice(0, 60), note: sig.note });
    seenHeaders.add(sig.header);
  }
  const st = Number(status);
  const unauthStatus = UNAUTH_STATUSES.includes(st);
  const flagged = signals.length > 0 && unauthStatus;
  const reason = flagged
    ? `edge-generated behavior on an unauthenticated ${st} response (${[...new Set(signals.map((s) => s.id))].join(', ')}) — the tested behavior is the gate's own challenge, not application behavior: high duplicate/non-impact risk`
    : signals.length ? 'edge headers present but the tested status is not an unauth challenge — not flagged'
      : 'no edge-generation signatures in the tested response';
  return { edge: signals.length > 0, unauthStatus, flagged, signals, reason };
}

// parseHttpEvidence(evidence) → [{ status, headers }] — every HTTP response block found
// in a finding's stored evidence text, so the edge detector can run on the SAME exchange
// the claim rests on (draftReports feeds finding.evidence through this).
export function parseHttpEvidence(evidence) {
  const text = String(evidence || '');
  const out = [];
  const re = /HTTP\/\d(?:\.\d)?\s+(\d{3})\b[^\n]*\n((?:[A-Za-z0-9-]+\s*:[^\n]*\n?)*)/g;
  let m;
  while ((m = re.exec(text)) && out.length < 20) out.push({ status: Number(m[1]), headers: m[2] || '' });
  return out;
}

// ---------------------------------------------------------- internal dedup (SimHash)
// 64-bit SimHash over word tokens — near-duplicate detection against our own prior
// drafts/reports, so a re-file against a sibling host is NOTED, never silent.
const STOP = new Set(['the', 'and', 'for', 'with', 'that', 'this', 'from', 'are', 'was', 'were', 'has', 'have', 'not', 'http', 'https', 'www', 'com', 'net']);
function tokens(text) {
  return (String(text || '').toLowerCase().match(/[a-z0-9][a-z0-9.-]{2,}/g) || [])
    .filter((t) => !STOP.has(t));
}
export function simhash64(text) {
  const bits = new Array(64).fill(0);
  for (const tok of tokens(text)) {
    const h = createHash('sha256').update(tok).digest();
    for (let i = 0; i < 64; i++) {
      const bit = (h[i >> 3] >> (i & 7)) & 1;
      bits[i] += bit ? 1 : -1;
    }
  }
  let fp = 0n;
  for (let i = 0; i < 64; i++) if (bits[i] > 0) fp |= (1n << BigInt(i));
  return fp;
}
export function hamming64(a, b) {
  let x = (a ^ b), n = 0;
  while (x) { n += Number(x & 1n); x >>= 1n; }
  return n;
}
export const DEDUP_THRESHOLD = 14; // of 64 bits — near-duplicate, not merely topical
// dedupScan(draftText, corpus:[{name, text}]) → ranked near-dupes { name, distance }
export function dedupScan(draftText, corpus = []) {
  const mine = simhash64(draftText);
  if (tokens(draftText).length < 40) return { matches: [], note: 'draft too short for a meaningful SimHash — dedup skipped honestly' };
  const matches = [];
  for (const doc of corpus) {
    if (!doc || tokens(doc.text).length < 40) continue;
    const distance = hamming64(mine, simhash64(doc.text));
    if (distance <= DEDUP_THRESHOLD) matches.push({ name: doc.name, distance });
  }
  matches.sort((a, b) => a.distance - b.distance);
  return { matches: matches.slice(0, 10) };
}

// ---------------------------------------------------------- hacktivity candidate ranking
// Token-overlap scoring of a finding's signature against disclosed-report metadata.
// queryTerms: the host's labels + the weakness class + the behavior signature words.
export function signatureTerms({ host, klass, signature } = {}) {
  const terms = new Set();
  for (const part of String(host || '').toLowerCase().split(/[^a-z0-9]+/)) if (part.length > 2 && !['com', 'net', 'org', 'www'].includes(part)) terms.add(part);
  if (klass && klass !== 'other') terms.add(klass);
  for (const w of tokens(signature)) terms.add(w);
  return [...terms];
}
export function rankCandidates(terms, candidates = []) {
  const scored = [];
  for (const c of candidates) {
    const hay = `${c.title || ''} ${c.weakness || ''} ${c.cwe || ''}`.toLowerCase();
    let hits = 0;
    for (const t of terms) if (hay.includes(t.toLowerCase())) hits++;
    const score = terms.length ? hits / terms.length : 0;
    scored.push({ ...c, score: Math.round(score * 100) / 100, matchedTerms: terms.filter((t) => hay.includes(t.toLowerCase())) });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored;
}
export const CANDIDATE_THRESHOLD = 0.3; // fraction of signature terms matched

// ---------------------------------------------------------- hacktivity response reader
// The shape VERIFIED LIVE 2026-08-31 (unauthenticated, through the ghost chain):
//   data.search.nodes[] = HacktivityDocument { _id, cwe, disclosed_at, severity_rating,
//     report { id, title, url, weakness { name }, team { handle, name } } }
// The reader ALSO tolerates flat variants (title/url on the node itself). Whatever it
// cannot parse lands EMPTY with a named gap — candidate reports are NEVER invented.
export function parseHacktivitySearch(raw, gaps = []) {
  let doc = raw;
  if (typeof raw === 'string') { try { doc = JSON.parse(raw); } catch { gaps.push('hacktivity response was not valid JSON — parsed as EMPTY (nothing invented)'); return []; } }
  if (!doc || typeof doc !== 'object') { gaps.push('hacktivity response was not an object — parsed as EMPTY'); return []; }
  if (Array.isArray(doc.errors) && doc.errors.length) gaps.push(`hacktivity GraphQL returned ${doc.errors.length} error(s): ${String(doc.errors[0] && doc.errors[0].message || doc.errors[0]).slice(0, 120)}`);
  let nodes = null;
  if (doc.data && doc.data.search && Array.isArray(doc.data.search.nodes)) nodes = doc.data.search.nodes;
  else if (doc.data && Array.isArray(doc.data.nodes)) nodes = doc.data.nodes;
  else if (Array.isArray(doc.nodes)) nodes = doc.nodes;
  else if (Array.isArray(doc.reports)) nodes = doc.reports;
  if (!nodes) { gaps.push('hacktivity response arrived in an unrecognized shape — parsed as EMPTY; check the query against the live schema (H1_GRAPHQL in tools/novelgate.mjs)'); return []; }
  const out = [];
  for (const n of nodes) {
    if (!n || typeof n !== 'object') continue;
    const rep = (n.report && typeof n.report === 'object') ? n.report : n;
    const title = rep.title || n.title;
    const url = rep.url || n.url || (n._id ? `https://hackerone.com/reports/${n._id}` : null);
    if (!title && !url) { gaps.push('a hacktivity node carried neither title nor url — skipped (never invented)'); continue; }
    out.push({
      id: String(n._id || (url && url.match(/(\d+)\s*$/)?.[1]) || rep.id || ''),
      title: String(title || url),
      url: url || null,
      weakness: (rep.weakness && rep.weakness.name) || n.weakness || null,
      cwe: n.cwe || null,
      date: n.disclosed_at || n.submitted_at || null,
      severity: n.severity_rating || null,
      team: (rep.team && (rep.team.handle || rep.team.name)) || null,
    });
  }
  return out;
}

// ------------------------------------------------------------------ the assessment
// assess({ klass, platform, draftText, status, headers, hacktivity, dedupMatches })
// hacktivity: null (offline draft — PENDING) | { ok:true, candidates } | { ok:false, error, reason }
export function assess({ klass, platform, draftText = '', status, headers, hacktivity = null, dedupMatches = [] } = {}) {
  const reasons = [];
  const k = klass || classifyWeakness(draftText);
  const impact = impactEvidence(k, draftText, { platform });
  const edge = detectEdgeGenerated({ status, headers });

  // 1) BLOCKED — the hard bars (never-submittable class, platform-ineligible class, or
  // missing class-required impact proof — which also covers edge-flagged-without-proof).
  if (!impact.ok) {
    reasons.push(`impact bar: ${impact.reason}`);
    return { verdict: 'BLOCKED', reasons, klass: k, impact, edge, dedupMatches, hacktivity: summarizeHack(hacktivity) };
  }
  if (edge.flagged) reasons.push(`${edge.reason} — the ${impact.required || 'class'} impact proof IS present, so the draft survives the bar, but the operator must confirm the tested behavior is the application's, not the gate's`);

  // 2) UNVERIFIABLE — the hacktivity search FAILED. Stated, never faked.
  if (hacktivity && hacktivity.ok === false) {
    reasons.push(`hacktivity duplicate search FAILED (${hacktivity.error}: ${hacktivity.reason}) — duplicate status is UNVERIFIABLE; re-run the search before submitting (fail-loud, never silently skipped)`);
    return { verdict: 'UNVERIFIABLE', reasons, klass: k, impact, edge, dedupMatches, hacktivity: summarizeHack(hacktivity) };
  }

  // 3) REVIEW-NEEDED — candidate duplicates (public or internal).
  const candidates = hacktivity && hacktivity.ok ? (hacktivity.candidates || []) : [];
  const strong = candidates.filter((c) => (c.score || 0) >= CANDIDATE_THRESHOLD);
  if (strong.length) reasons.push(`${strong.length} disclosed report(s) match this finding's signature — the operator MUST read them and rule out a duplicate before submitting`);
  if (dedupMatches && dedupMatches.length) reasons.push(`${dedupMatches.length} of OUR OWN prior drafts/reports are near-duplicates (SimHash) — re-filing a sibling host without noting it burns program goodwill`);
  if (strong.length || (dedupMatches && dedupMatches.length) || edge.flagged) {
    return { verdict: 'REVIEW-NEEDED', reasons, klass: k, impact, edge, candidates, dedupMatches, hacktivity: summarizeHack(hacktivity) };
  }

  // 4) CLEAR — nothing matched; hacktivity PENDING (offline draft) is stated, not hidden.
  if (hacktivity === null) reasons.push('hacktivity duplicate search NOT YET RUN (offline draft) — run tools/novelgate.mjs check before queueing/submitting');
  else reasons.push('no disclosed-report candidates above threshold and no internal near-duplicates');
  return { verdict: 'CLEAR', reasons, klass: k, impact, edge, candidates, dedupMatches, hacktivity: summarizeHack(hacktivity) };
}
function summarizeHack(h) {
  if (h === null) return { state: 'PENDING' };
  if (h.ok === false) return { state: 'FAILED', error: h.error, reason: h.reason };
  return { state: 'OK', candidates: (h.candidates || []).length, gaps: h.gaps || [] };
}

// ------------------------------------------------------------------ markdown section
export function renderNoveltySection(a, { program, host, signature, corpusSize, command } = {}) {
  const L = [];
  L.push('', '---', '', '## Novelty check (novelgate)', '', NOVELTY_MARKER, '');
  L.push(`- verdict: **${a.verdict}**`);
  if (program || host) L.push(`- subject: ${program || 'program?'} · ${host || 'host?'}`);
  L.push(`- weakness class: **${a.klass}**${a.impact && a.impact.required ? ` (impact bar: ${a.impact.required} — ${a.impact.ok ? 'MET' : 'MISSING'})` : ''}`);
  L.push(`- edge-generated behavior: ${a.edge && a.edge.flagged ? `**FLAGGED** — ${a.edge.signals.map((s) => `${s.header}: ${s.value}`).join('; ')}` : 'not detected on the tested response'}`);
  if (a.hacktivity) {
    const h = a.hacktivity;
    if (h.state === 'PENDING') L.push(`- hacktivity duplicate search: **PENDING** — run \`${command || 'node tools/novelgate.mjs check …'}\` before submitting`);
    else if (h.state === 'FAILED') L.push(`- hacktivity duplicate search: **UNVERIFIABLE** — ${h.error}: ${h.reason}`);
    else L.push(`- hacktivity duplicate search: ${h.candidates} candidate(s)${h.gaps && h.gaps.length ? ` (${h.gaps.length} parse gap(s) — see tool output)` : ''}`);
  }
  if (a.candidates && a.candidates.length) {
    L.push('', '| candidate duplicate | weakness | disclosed | score |', '| --- | --- | --- | --- |');
    for (const c of a.candidates.slice(0, 8)) L.push(`| [${c.id} — ${c.title}](${c.url || ''}) | ${c.weakness || c.cwe || '?'} | ${c.date || '?'} | ${c.score} |`);
  }
  L.push(`- internal dedup: ${corpusSize !== undefined ? `${corpusSize} prior draft(s)/report(s) scanned, ` : ''}${(a.dedupMatches || []).length} near-duplicate(s)${(a.dedupMatches || []).length ? ` — ${a.dedupMatches.map((m) => `${m.name} (distance ${m.distance})`).join(', ')}` : ''}`);
  for (const r of a.reasons || []) L.push(`- ${r}`);
  L.push('', '_Limitations: this gate searches PUBLIC disclosed reports only — undisclosed duplicates are unsearchable, so the gate reduces but CANNOT eliminate duplicate risk. A CLEAR verdict is not a promise of novelty._', '');
  return L.join('\n');
}

// parseNoveltySection(md) → { present, verdict } — queueProgram's machine check.
export function parseNoveltySection(md) {
  const text = String(md || '');
  if (!text.includes(NOVELTY_MARKER)) return { present: false, verdict: null };
  const m = text.match(/- verdict: \*\*(CLEAR|REVIEW-NEEDED|UNVERIFIABLE|BLOCKED)\*\*/);
  return { present: true, verdict: m ? m[1] : null };
}
