// VARVEL — target defense fingerprinting + per-target stealth calibration.
//
// RedAmon NAMES this exact problem in its whitepaper — "--max-rate 50 against this
// hardened target but --max-rate 200 against a different less-monitored one" — then
// PUNTS it to the LLM ("context-sensitive judgment that hard limits would over-
// constrain"). VARVEL makes it a MEASURED decision: passively fingerprint the target's
// defensive stack (WAF/CDN vendor, rate-limit signals, bot-challenge, security-header
// maturity) from responses we already receive, then auto-calibrate the ENFORCED stealth
// profile + noise budget to that target. Adaptive stealth, not a static prompt.
//
// DISCOVERY + CALIBRATION only. It reads what the target volunteers and chooses to be
// appropriately quiet on an AUTHORIZED engagement — it does NOT defeat, bypass, or evade
// any control; every request is still recorded in the Enclave's tamper-evident audit.

import http from 'node:http';
import https from 'node:https';
import { budgetPreset } from './budget.mjs';

// Well-known WAF/CDN header + cookie + block-page signatures (public fingerprints, in the
// spirit of wafw00f). `monitoring` = how strongly this stack implies an actively-watched
// target (→ how much we should quieten).
const DEFENSES = [
  { id: 'cloudflare', vendor: 'Cloudflare', kind: 'waf-cdn', monitoring: 'high',
    header: { server: /cloudflare/i, 'cf-ray': /\S/, 'cf-cache-status': /\S/, 'cf-mitigated': /\S/ },
    cookie: /__cf(uid|_bm|duid)|cf_clearance|cf_bm/i, body: /attention required!|cloudflare|cf-error-details|__cf_chl/i },
  { id: 'akamai', vendor: 'Akamai', kind: 'waf-cdn', monitoring: 'high',
    header: { server: /akamaighost/i, 'x-akamai-transformed': /\S/, 'x-akamai-request-id': /\S/, 'akamai-grn': /\S/ },
    body: /akamai|reference #\d+\.\w+/i },
  { id: 'imperva', vendor: 'Imperva / Incapsula', kind: 'waf', monitoring: 'high',
    header: { 'x-iinfo': /\S/, 'x-cdn': /incapsula/i },
    cookie: /incap_ses|visid_incap|nlbi_/i, body: /incapsula|_Incapsula_Resource/i },
  { id: 'sucuri', vendor: 'Sucuri CloudProxy', kind: 'waf', monitoring: 'high',
    header: { server: /sucuri/i, 'x-sucuri-id': /\S/, 'x-sucuri-cache': /\S/ },
    body: /sucuri|access denied - sucuri/i },
  { id: 'f5', vendor: 'F5 BIG-IP ASM', kind: 'waf', monitoring: 'high',
    header: { server: /big-?ip/i },
    cookie: /BIGipServer|^TS[0-9a-f]{6,}/i, body: /the requested url was rejected/i },
  { id: 'aws', vendor: 'AWS CloudFront / ALB / WAF', kind: 'waf-cdn', monitoring: 'med',
    header: { 'x-amz-cf-id': /\S/, 'x-amzn-requestid': /\S/, 'x-amzn-trace-id': /\S/, server: /awselb|cloudfront/i, via: /cloudfront/i } },
  { id: 'azure', vendor: 'Azure Front Door / App Gateway', kind: 'waf-cdn', monitoring: 'med',
    header: { 'x-azure-ref': /\S/, 'x-msedge-ref': /\S/ } },
  { id: 'fastly', vendor: 'Fastly', kind: 'cdn', monitoring: 'med',
    header: { 'x-fastly-request-id': /\S/, 'x-served-by': /cache-/i, 'x-timer': /^S\d/ } },
  { id: 'modsecurity', vendor: 'ModSecurity', kind: 'waf', monitoring: 'med',
    header: { server: /mod_security|modsecurity/i }, body: /mod_security|generated by mod_security|not acceptable!/i },
  // Our own practice target's edge defense (targets/premium-hard.mjs) — detected like any
  // other WAF so 'auto' calibration trains against a REAL shielded target, headers included.
  { id: 'axiom-shield', vendor: 'Axiom Shield (custom edge WAF)', kind: 'waf', monitoring: 'high',
    header: { 'x-axiom-shield': /\S/ } },
];

const toNum = (v) => { const n = Number(Array.isArray(v) ? v[0] : v); return Number.isFinite(n) ? n : undefined; };
function cookieHay(headers) { const sc = headers && headers['set-cookie']; return Array.isArray(sc) ? sc.join('; ') : String(sc || ''); }

function matchDefense(def, headers, body) {
  const signals = [];
  if (def.header) for (const [name, re] of Object.entries(def.header)) {
    const v = headers && headers[name];
    if (v != null && re.test(Array.isArray(v) ? v.join('; ') : String(v))) signals.push(`header:${name}`);
  }
  if (def.cookie && def.cookie.test(cookieHay(headers))) signals.push('cookie');
  if (def.body && body && def.body.test(body)) signals.push('block-page');
  return signals;
}

// Rate-limit disclosure from response headers (or a 429). Absence ≠ "no limit"; presence
// is a hard signal that the target throttles and we should stay under it.
function rateLimitInfo(headers = {}, status) {
  const limit = headers['x-ratelimit-limit'] ?? headers['ratelimit-limit'] ?? headers['x-rate-limit-limit'];
  const remaining = headers['x-ratelimit-remaining'] ?? headers['ratelimit-remaining'] ?? headers['x-rate-limit-remaining'];
  const reset = headers['x-ratelimit-reset'] ?? headers['ratelimit-reset'];
  const retryAfter = headers['retry-after'];
  if (limit == null && remaining == null && reset == null && retryAfter == null && status !== 429) return null;
  return { limit: toNum(limit), remaining: toNum(remaining), reset: toNum(reset), retryAfter: toNum(retryAfter), throttled: status === 429 || retryAfter != null };
}

function challengeInfo(status, headers = {}, body = '') {
  const markers = [];
  if (headers['cf-mitigated']) markers.push('cf-mitigated');
  if (/hcaptcha|recaptcha|challenge-platform|__cf_chl|jschl|are you a human|verify you are human/i.test(body || '')) markers.push('bot-challenge');
  return markers.length ? { status, markers } : null;
}

function securityHeaders(headers = {}) {
  const s = [];
  if (headers['strict-transport-security']) s.push('hsts');
  if (headers['content-security-policy']) s.push('csp');
  if (headers['x-frame-options']) s.push('xfo');
  if (headers['x-content-type-options']) s.push('xcto');
  if (headers['permissions-policy'] || headers['feature-policy']) s.push('permissions-policy');
  return s;
}

// Pure: given ONE response ({status, headers, body}), fingerprint its defensive stack.
export function fingerprintDefenses({ status, headers = {}, body = '' } = {}) {
  const defenses = [];
  for (const def of DEFENSES) {
    const signals = matchDefense(def, headers, body);
    if (signals.length) defenses.push({ id: def.id, vendor: def.vendor, kind: def.kind, monitoring: def.monitoring, signals });
  }
  return { defenses, rateLimit: rateLimitInfo(headers, status), challenge: challengeInfo(status, headers, body), securityHeaders: securityHeaders(headers), status };
}

// Merge fingerprints from several responses (a WAF often only shows its block page on the
// "attack-ish" miss, not the friendly root) — union defenses (max signals), keep any
// rate-limit/challenge seen, union security headers.
export function mergeFingerprints(...fps) {
  const byId = new Map();
  let rateLimit = null, challenge = null; const sec = new Set();
  for (const fp of fps) {
    if (!fp) continue;
    for (const d of fp.defenses || []) { const p = byId.get(d.id); if (!p || d.signals.length > p.signals.length) byId.set(d.id, d); }
    if (fp.rateLimit && (!rateLimit || fp.rateLimit.throttled)) rateLimit = fp.rateLimit;
    if (fp.challenge && (!challenge || (fp.challenge.markers || []).length > (challenge.markers || []).length)) challenge = fp.challenge;
    for (const h of fp.securityHeaders || []) sec.add(h);
  }
  return { defenses: [...byId.values()], rateLimit, challenge, securityHeaders: [...sec] };
}

// Pure: fingerprint → a recommended ENFORCED-stealth profile + budget + human reasons.
// Calibration only ever quietens (never louder) as evidence of monitoring accrues — the
// safe direction on an authorized test. No evidence → 'normal' (a fast sweep is fine, but
// absence of a WAF header isn't proof the target isn't watched).
export function calibrateStealth(fp) {
  const order = ['loud', 'normal', 'quiet', 'paranoid'];
  let level = 1; const reasons = [];
  const bump = (to, why) => { if (to > level) level = to; if (why) reasons.push(why); };
  const defs = fp.defenses || [];
  const highWaf = defs.filter((d) => d.monitoring === 'high');
  const anyWaf = defs.filter((d) => d.kind === 'waf' || d.kind === 'waf-cdn');
  const cdnOnly = defs.filter((d) => d.kind === 'cdn');

  if (highWaf.length) bump(2, `${highWaf.map((d) => d.vendor).join(', ')} (actively-monitored WAF) — go low-and-slow`);
  else if (anyWaf.length) bump(2, `${anyWaf.map((d) => d.vendor).join(', ')} WAF present — reduce footprint`);
  else if (cdnOnly.length) bump(1, `${cdnOnly.map((d) => d.vendor).join(', ')} CDN in front`);

  if (fp.rateLimit) {
    if (fp.rateLimit.throttled) bump(3, 'already throttled (429 / Retry-After) — back right off');
    else bump(2, `target advertises rate limits (limit ${fp.rateLimit.limit ?? '?'}) — stay under them`);
  }
  if (fp.challenge) bump(3, `bot-challenge active (${fp.challenge.markers.join(', ')}) — minimal footprint`);
  if ((fp.securityHeaders || []).length >= 3) bump(2, 'hardened security headers (mature, likely-monitored target)');
  if (!defs.length && !fp.rateLimit && !fp.challenge) reasons.push('no WAF / CDN / rate-limit detected — a faster sweep is acceptable');

  const recommended = order[level];
  const b = budgetPreset(recommended);
  const rateHint = fp.rateLimit && fp.rateLimit.limit ? Math.max(1, Math.floor(fp.rateLimit.limit * 0.5)) : null; // stay well under an advertised limit
  return { recommended, level, reasons, rateHint, budget: { maxNoise: b.maxNoise, peakCeiling: b.peakCeiling } };
}

const CAP = 8192;
function get(origin, path, timeout, agents) {
  return new Promise((resolve) => {
    let u; try { u = new URL(path, origin); } catch { return resolve(null); }
    const lib = u.protocol === 'https:' ? https : http;
    let body = '', done = false;
    const fin = (v) => { if (!done) { done = true; clearTimeout(t); resolve(v); } };
    const req = lib.request({ hostname: u.hostname, port: u.port || (u.protocol === 'https:' ? 443 : 80), path: u.pathname + u.search, method: 'GET', timeout, rejectUnauthorized: false, agent: agents ? (u.protocol === 'https:' ? agents.httpsAgent : agents.httpAgent) : undefined, headers: { 'user-agent': 'VARVEL-profiler', accept: '*/*' } }, (r) => {
      r.on('data', (d) => { if (body.length < CAP) body += d.toString('latin1', 0, Math.max(0, CAP - body.length)); });
      r.on('end', () => fin({ status: r.statusCode, headers: r.headers, body }));
    });
    const t = setTimeout(() => { try { req.destroy(); } catch {} fin(null); }, timeout);
    req.on('timeout', () => { try { req.destroy(); } catch {} fin(null); });
    req.on('error', () => fin(null));
    req.end();
  });
}

// Passive-first stack detection: the root response + one benign non-existent path (to
// elicit a WAF block page). Two GETs — deliberately quiet, since it would be ironic to be
// loud while measuring how to stay quiet. Returns the merged fingerprint + calibration.
export async function detectStack(base, { timeout = 2500, rand = Math.random, agents = null } = {}) {
  let origin;
  try { const u = new URL(base); if (!/^https?:$/.test(u.protocol)) throw new Error('proto'); origin = u.origin; }
  catch { return null; }
  const root = await get(origin, '/', timeout, agents);
  const rnd = '/' + Array.from({ length: 10 }, () => 'abcdefghijklmnopqrstuvwxyz'[Math.floor(rand() * 26)]).join('');
  const miss = await get(origin, rnd, timeout, agents);
  const merged = mergeFingerprints(root ? fingerprintDefenses(root) : null, miss ? fingerprintDefenses(miss) : null);
  return { base: origin, ...merged, calibration: calibrateStealth(merged), probes: (root ? 1 : 0) + (miss ? 1 : 0) };
}
